### ISSUE TITLE
RDNA tests failing

### ISSUE THREAD

**Issue by gartnera** [tinygrad/tinygrad#1031]
`GPU=1 RDNA=1 FORWARD_ONLY=1 python3 test/test_ops.py TestOps.test_add` hangs after 18892242b006785d4e92abae7c792e7874c17df9 with dmesg `amdgpu: sq_intr: error, detail 0x00000000, type 2, sh 1, priv 1, wave_id 1, simd_id 0, wgp_id 0`

Bisected with:

```
#!/bin/bash

set -e

export GPU=1
export RDNA=1
export FORWARD_ONLY=1
export DEBUG=5

timeout 5s python3 test/test_ops.py TestOps.test_add
```

**Comment by geohot** [comment]
RDNA isn't well supported yet. There's a $1000 bounty to fix this.

**Comment by wozeparrot** [comment]
Tracking at #1698
