### ISSUE TITLE
One dimensional `Tensor` doesn't broadcast for `Embedding`. Produces `AssertionError`

### ISSUE THREAD

**Issue by big-c-note** [tinygrad/tinygrad#1096]
Just diving into tinygrad. I'm migrating an architecture written in pytorch to tinygrad. Tried on 
- MPS and CPU. 
- Python 3.11. 
- On a Mac M2

#### Minimal example to reproduce
```
import torch

cat = torch.nn.Embedding(8, 32)
cat(torch.arange(8))
```
New shape is `(8,32)`

```
from tinygrad.nn import Embedding, Tensor

cat = Embedding(8, 32)
cat(Tensor.arange(8))
```
Produces an `AssertionError` in the `ShapeTracker` class `expand` method. 
```
assert len(new_shape) == len(self.views[-1].shape)
```

The following works
```
from tinygrad.nn import Embedding, Tensor

cat = Embedding(8, 32)
cat(Tensor.stack([Tensor.arange(8)]))
```
Which has shape `(1, 8, 32)`

I can run a debugger through it later, but maybe this is expected due to a explicit philosophy? May be related to #967 or a more general lack of support for broadcasting.

By the way, love the vision for the project.

**Comment by big-c-note** [comment]
Current use case is creating a position embedding

**Comment by wozeparrot** [comment]
You should be able to do this that's a little bit cleaner

```py
from tinygrad.tensor import Tensor
from tinygrad.nn import Embedding

cat = Embedding(8, 32)
cat(Tensor.arange(8).reshape(1, 8))
```

The embedding that's currently implemented is designed for batched inputs, as thats the most common use case for embedding, and for unbatched inputs you can just reshape before and after.
