### ISSUE TITLE
[Bug] load_single_weight in extra/utils.py throws an AttributeError

### ISSUE THREAD

**Issue by tricky-labyrinth** [tinygrad/tinygrad#1140]
It happens on [L135 or L136](https://github.com/geohot/tinygrad/blob/d363d25ee212cfac1e5bf91c1802f5a22274958a/extra/utils.py#L135), because t.lazydata.op.arg is a tuple that can't have attributes set.

Easiest way to see this is to try to run examples/convnext.py.

**Comment by fabiogomez11c** [comment]
I was debugging a bit into the process. It seems to me that the [downloaded model/weights](https://dl.fbaipublicfiles.com/convnext/convnext_{version}_1k_224_ema.pth) comes with that tuple so the attribute can't be set, and something similar happens to all the tensors where the `Tensor.lazydata.op.arg` is either a Tuple or None type.

**Comment by chenyuxyz** [comment]
closing as obsolete. extra/utils.py has been refactored and removed
