### ISSUE TITLE
Norm Fusion ($2000 bounty)

### ISSUE THREAD

**Issue by geohot** [tinygrad/tinygrad#1146]
![Screenshot_2023-07-04_at_1 49 02_PM](https://github.com/geohot/tinygrad/assets/72895/5fd74144-85a9-4871-88c2-aea99bfd30cd)

Kernels 8,9,10,11 should be fused into one. This requires quite a bit of thinking about the spec for the AST, and probably a refactor of `lazy.py` and parts of the `Linearizer` to support the added complexity.

This is relevant to #1137.

Currently, the definition of an AST which gets compiled to a single kernel is MovementOps -> ElementwiseOps -> ReduceOps -> ElementwiseOps. It has two shapes, an input shape and an output shape, where the output shape can replace some of the input dimensions with ones.

We have explicitly coded this idea of a "late reduce" in the Linearizer and step one of this might be refactoring that into something generic.

**Comment by anveshrd** [comment]
Can I work on this ? Is it still open ?
