### ISSUE TITLE
Fix view merging for masked views

### ISSUE THREAD

**Issue by geohot** [tinygrad/tinygrad#1152]
[  if vm2.mask: return None  # this isn't supported yet](https://github.com/geohot/tinygrad/blob/c5aea13a6503f07e93e46f345fbf52da3b54d28d/tinygrad/shape/shapetracker.py#L89)

**Comment by g1y5x3** [comment]
While looking into it, I think there's also a bug at 
[if view.contiguous: return new_view, False # NOTE: if it's contiguous it can't have an offset](https://github.com/tinygrad/tinygrad/blob/c5aea13a6503f07e93e46f345fbf52da3b54d28d/tinygrad/shape/shapetracker.py#L115C23-L115C29)
where the mask index was not being tracked

Here is an example:
```
>>> c = ShapeTracker((4,2))
>>> c.views[-1].mask = ((0,2))
>>> c
ShapeTracker(shape=(4, 2), views=[View((4, 2), (2, 1), 0, (1, 1))])
>>> c.reshape((2,4))
ShapeTracker(shape=(2, 4), views=[View((2, 4), (4, 1), 0, None)])
```

**Comment by geohot** [comment]
Err, views are immutable unless you violently reach inside them and change them :)

**Comment by roelofvandijk** [comment]
Comes for free once Views are NamedTuples - they're immutable.
