### ISSUE TITLE
Missing int32 test coverage

### ISSUE THREAD

**Issue by dc-dc-dc** [tinygrad/tinygrad#1170]
Int32 dtype test coverage is missing, add int32 tests to `test/test_dtype.py`.

In part should also resolve the issues with `ops_cpu`, as numpy will upcast an op between int32 and float32 to float64

**Comment by FrostyTheSouthernSnowman** [comment]
Currently working on test coverage. Once that is complete, I will add the upcast from int32 and float32 to float32.

**Comment by FrostyTheSouthernSnowman** [comment]
Turned out I also needed to add match_types call to FusedOps.MULACC. I did that inside the einsum_mulacc function

**Comment by FrostyTheSouthernSnowman** [comment]
that was actually a bad idea. Code is fixed now and ready to be merged. This issue can be closed as soon as that merge happens
