### ISSUE TITLE
Incorrect file paths in datasets

### ISSUE THREAD

**Issue by jla524** [tinygrad/tinygrad#1176]
```
jacky@ephphatha tinygrad % python3 extra/datasets/librispeech.py
Traceback (most recent call last):
  File "/Users/jacky/fun/tinygrad/extra/datasets/librispeech.py", line 19, in <module>
    with open(BASEDIR / "dev-clean-wav.json") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jacky/fun/tinygrad/extra/extra/datasets/librispeech/dev-clean-wav.json'
```

**Comment by madt2709** [comment]
Did you follow the instructions written above? eg

"""
The dataset has to be downloaded manually from https://www.openslr.org/12/ and put in `extra/datasets/librispeech`.
For mlperf validation the dev-clean dataset is used.

Then all the flacs have to be converted to wav using something like:
```fish
for file in $(find * | grep flac); do ffmpeg -i $file -ar 16k "$(dirname $file)/$(basename $file .flac).wav"; done
```

Then this [file](https://github.com/mlcommons/inference/blob/master/speech_recognition/rnnt/dev-clean-wav.json) has to also be put in `extra/datasets/librispeech`.
"""
