### ISSUE TITLE
Fix constant folding for Tensor([3])

### ISSUE THREAD

**Issue by geohot** [tinygrad/tinygrad#1178]
I believe now 1-D numpy arrays aren't being constant folded, they should be.

Like `Tensor(3)` works but `Tensor([3])` doesn't.

We should also add a test to prevent this regression in the future.

**Comment by wozeparrot** [comment]
Can be closed now.

**Comment by chenyuxyz** [comment]
reopening this

The issue is that `a = Tensor(3).reshape(1)` is a reshape of 0 dim Tensor, thus different from `b = Tensor([3])`.

reshape itself is easy to solve, but need some thinking about all the possible cases that a non-load op can/need to create a buffer
