### ISSUE TITLE
examples/simple_conv_bn.py throws an exception when run at OPT=0

### ISSUE THREAD

**Issue by tricky-labyrinth** [tinygrad/tinygrad#1202]
When OPT>=1, no exceptions are thrown. Both cases of this happening were on CUDA backend.

When I did this, I got a pyopencl._cl.MemoryError, but fluffy got a pycuda._driver.LogicError instead.

**Comment by ZoneTwelve** [comment]
I have the same issues with the Metal backend.
but I don't know why you want to set OPT=0, according by [docs/env_vars.md](https://github.com/tinygrad/tinygrad/blob/master/docs/env_vars.md#global-variables) you should not set OPT=0.
