### ISSUE TITLE
Perpetual Bounty: llama Python runtime 20%+ faster on M1 -- $200+

### ISSUE THREAD

**Issue by geohot** [tinygrad/tinygrad#1209]
Last bounty was $1000 for 100%, so it scales linearly. Minimum I'll consider is 20% and $200, but for 40% we'll pay $400 etc... @roelofvandijk 

Gains must not come from changing LLaMA or using the JIT. Only the "ran model" time matters, the GPU sync time is a different problem that you don't have to worry about for this bounty. Will be evaluated on M1 Max python3.11 with asserts turned off as below.

Will not merge anything that negatively impacts readability or adds tons of lines. Benchmark timing is 99.58 ms, so 82.98 ms is needed to be eligible.

```
kafka@tubby:~/fun/tinygrad$ python3.11 -O examples/llama.py --prompt "Hello." --count 10 --temperature 0 --timing
using METAL backend
ram used: 13.48 GB, freqs_cis                                         : 100%|███████████████████████████████████████████████████████████████████████████████| 292/292 [00:04<00:00, 67.66it/s]
loaded weights in 4322.95 ms, 13.48 GB loaded at 3.12 GB/s
Hello.
ran model in 1188.19 ms
sync in 130.40 ms
 I
ran model in 185.39 ms
sync in 4.61 ms
'
ran model in 101.04 ms
sync in 3.80 ms
m
ran model in 102.47 ms
sync in 3.78 ms
 a
ran model in 109.10 ms
sync in 3.87 ms
 
ran model in 99.58 ms
sync in 3.88 ms
2
ran model in 104.83 ms
sync in 3.74 ms
0
ran model in 102.63 ms
sync in 3.62 ms
 year
ran model in 113.94 ms
sync in 3.75 ms
 old
ran model in 102.66 ms
sync in 3.71 ms
```

**Comment by roelofvandijk** [comment]
Minor semantic nit (if I am not mistaken): 
If 200ms->100ms is 100% speedup (2x as fast), 99.58ms->79.66ms is already a **25%** speedup.
A 20% speedup would be 82.98ms (99.58ms/120).

I'd like to give his a shot and see how far I can get with subtle changes and conceputal refactors.

**Comment by geohot** [comment]
Good point, updated

**Comment by cacaosteve** [comment]
I must be doing something wrong because I'm on a 2021 MacBook Pro M1 Max and it is using the CPU: (base) ➜  tinygrad git:(master) ✗ conda activate my_conda_env_with_py311
(my_conda_env_with_py311) ➜  tinygrad git:(master) ✗ python3.11 -O examples/llama.py --prompt "Hello." --count 10 --temperature 0 --timing
using CPU backend
using LLaMA-7B model
ram used: 13.48 GB, freqs_cis                                         : 100%|█████████| 292/292 [00:00<00:00, 8887.53it/s]
loaded weights in 239.09 ms, 13.48 GB loaded at 56.37 GB/s
Hello.
ran model in 51756.77 ms
sync in 12117.49 ms
 I
ran model in 46876.28 ms
sync in 11304.77 ms
'
ran model in 45436.27 ms
sync in 11041.51 ms

**Comment by cacaosteve** [comment]
I saw something on simonwenkel.com that said do "conda install -c conda-forge pocl pyopencl clinfo" to use GPU. putting PYOPENCL_COMPILER_OUTPUT=1 in cache.py or llama.py doesn't seem to do anything, neither does setting that environment variable. and my ran model times are still way more than yours. 786.50 ms at best. (my_conda_env_with_py311) ➜  tinygrad git:(master) ✗ python3.11 -O examples/llama.py --prompt "Hello." --count 10 --temperature 0 --timing
using GPU backend
using LLaMA-7B model
ram used: 13.48 GB, freqs_cis                                         : 100%|██████████████████████| 292/292 [00:00<00:00, 6212.08it/s]
loaded weights in 69.41 ms, 13.48 GB loaded at 194.19 GB/s
Hello.
/Users/steve/miniforge3/envs/my_conda_env_with_py311/lib/python3.11/site-packages/pyopencl/cache.py:495: CompilerWarning: Non-empty compiler output encountered. Set the environment variable PYOPENCL_COMPILER_OUTPUT=1 to see more.
  _create_built_program_from_source_cached(
/Users/steve/miniforge3/envs/my_conda_env_with_py311/lib/python3.11/site-packages/pyopencl/cache.py:499: CompilerWarning: Non-empty compiler output encountered. Set the environment variable PYOPENCL_COMPILER_OUTPUT=1 to see more.
  prg.build(options_bytes, devices)
ran model in 32767.68 ms
sync in 5760.29 ms
 I
ran model in 422.49 ms
sync in 962.84 ms
'
ran model in 314.56 ms
sync in 786.50 ms
m
ran model in 203.72 ms
sync in 884.54 ms
 a
ran model in 292.95 ms
sync in 978.82 ms
 
ran model in 244.11 ms
sync in 875.56 ms
2
ran model in 212.70 ms
sync in 896.38 ms
0
ran model in 278.44 ms
sync in 833.53 ms
 year
ran model in 236.25 ms
sync in 956.24 ms
 old
ran model in 299.93 ms
sync in 875.82 ms
 male%

**Comment by cacaosteve** [comment]
after putting that variable in my .zshrc file: Hello.
/Users/steve/miniforge3/envs/my_conda_env_with_py311/lib/python3.11/site-packages/pyopencl/cache.py:495: CompilerWarning: Built kernel retrieved from cache. Original from-source build had warnings:
Build on <pyopencl.Device 'cpu' on 'Portable Computing Language' at 0x7fba3582c600> succeeded, but said:

warning: /Users/steve/.cache/pocl/kcache/tempfile_o47SpM.cl:1:26: unsupported OpenCL extension 'cl_khr_fp16' - ignoring

  _create_built_program_from_source_cached(
/Users/steve/miniforge3/envs/my_conda_env_with_py311/lib/python3.11/site-packages/pyopencl/cache.py:499: CompilerWarning: From-binary build succeeded, but resulted in non-empty logs:
Build on <pyopencl.Device 'cpu' on 'Portable Computing Language' at 0x7fba3582c600> succeeded, but said:

warning: /Users/steve/.cache/pocl/kcache/tempfile_o47SpM.cl:1:26: unsupported OpenCL extension 'cl_khr_fp16' - ignoring

  prg.build(options_bytes, devices)
/Users/steve/miniforge3/envs/my_conda_env_with_py311/lib/python3.11/site-packages/pyopencl/cache.py:495: CompilerWarning: Built kernel retrieved from cache. Original from-source build had warnings:
Build on <pyopencl.Device 'cpu' on 'Portable Computing Language' at 0x7fba3582c600> succeeded, but said:

warning: /Users/steve/.cache/pocl/kcache/tempfile_cSJIT0.cl:1:26: unsupported OpenCL extension 'cl_khr_fp16' - ignoring

  _create_built_program_from_source_cached(
/Users/steve/miniforge3/envs/my_conda_env_with_py311/lib/python3.11/site-packages/pyopencl/cache.py:499: CompilerWarning: From-binary build succeeded, but resulted in non-empty logs:
Build on <pyopencl.Device 'cpu' on 'Portable Computing Language' at 0x7fba3582c600> succeeded, but said:

warning: /Users/steve/.cache/pocl/kcache/tempfile_cSJIT0.cl:1:26: unsupported OpenCL extension 'cl_khr_fp16' - ignoring

**Comment by wozeparrot** [comment]
Can you open a discussion post for this or join the discord for help? Thanks!
