### ISSUE TITLE
Don't write to disk in the clang backend

### ISSUE THREAD

**Issue by wozeparrot** [tinygrad/tinygrad#1258]
Currently a race condition is possible: https://canary.discord.com/channels/1068976834382925865/1068976834928193609/1128683739946418277

![race condition pytest](https://github.com/tinygrad/tinygrad/assets/25372613/83713fe2-d30d-408a-8037-887c512d8242)

It's also a TODO item: https://github.com/tinygrad/tinygrad/blob/64d39188ad22574025eb6534727ed33d699b4348/tinygrad/runtime/ops_clang.py#L15

This is 100% possible to do on linux (see below), needs investigation for windows and mac.

![linux fix](https://github.com/tinygrad/tinygrad/assets/25372613/2dc7aa58-e19d-4fc4-b481-4dc68ce9b4f9)

**Comment by mixmaester** [comment]
maybe possible with io.BytesIO() ?

**Comment by ZenginU** [comment]
@wozeparrot,
I am new to this staff but I believe for macos we have mmap.mmap() in python and for windows we can create memory mapped file than get the handle with _get_osfhandle. Hope this is helpful

**Comment by xuky76** [comment]
/dev/shm isn't a thing on mac

- [shm_open(2)](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/shm_open.2.html)
- [https://docs.python.org/3/library/multiprocessing.shared_memory.html](https://docs.python.org/3/library/multiprocessing.shared_memory.html)

**Comment by WilliamTheHippo** [comment]
> maybe possible with io.BytesIO() ?

Sadly the `CDLL` constructor requires a filename for the shared object/library, and, from what I can tell, there's no option to specify a named stream or something; it needs a location on disk. Maybe it's some sort of guard against mangled/truncated streams?

Very frustrating, especially given the usual ease of piping around binary data between functions without needing to store it on disk.

**Comment by xando** [comment]
Hey I am trying to understand the comments above. 


from @mixmaester
>maybe possible with io.BytesIO() ?


from @xuky76  
>/dev/shm isn't a thing on mac 

and [TODO](https://github.com/tinygrad/tinygrad/blob/7cac5ea16c46ed936ede2e6a172ddc6c6259f9b8/tinygrad/runtime/ops_clang.py#L15) itself. 
> `TODO: is there a way to not write this to disk?`



Will all of those points, will not invalidate this [line](https://github.com/tinygrad/tinygrad/blob/7cac5ea16c46ed936ede2e6a172ddc6c6259f9b8/tinygrad/runtime/ops_clang.py#L17)? What I'm missing?

**Comment by wozeparrot** [comment]
Yea, the idea is that the clang backend won't need to write anything to disk anymore so that line would be unneeded.

**Comment by nilsimda** [comment]
Maybe a named pipe works here? Because BytesIO suffers from the problem of not having a filename on the OS, which is apparently needed for `ctypes.CDLL` and possibly for clang (I couldn't get to go to stdout with -).

**Comment by l-j-g** [comment]
would something like   #1426 work? 

executing from the lib from memory does not seem to be worth the squeeze and i don't think would even guarantee against the race condition?

**Comment by xuky76** [comment]
The race condition and the TODO are two separate issues.

The reasons I mentioned above is probably why the comment is a 'comment'.  

- `CDLL` expects a file and a named pipe is not a file. 

```python
OSError: dlopen(testpipe, 0x0006): tried: 'testpipe' (not a file), '/System/Volumes/Preboot/Cryptexes/OStestpipe' (no such file), '/opt/homebrew/lib/testpipe' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/testpipe' (no such file), '/usr/lib/testpipe' (no such file, not in dyld cache), 'testpipe' (not a file), '/usr/local/lib/testpipe' (no such file), '/usr/lib/testpipe' (no such file, not in dyld cache)
```

Pipes are also buffered so you'll see this on the other side.

```bash
(base) ➜  tinygrad git:(master) ✗ clang hello.c -o testpipe  
clang: error: unable to execute command: Broken pipe: 13
clang: error: linker command failed due to signal (use -v to see invocation)
```

I think if there were an easy fix for this (that is cross-platform), it would have already been done.

**Comment by prusnak** [comment]
I think it should be possible to use hardlinks, i.e.

``` python
os.link(A, B)
os.unlink(A)
```

instead of

``` python
os.rename(A, B)
```

AFAIK hardlinks are supported on Windows too these days.

**Comment by geohot** [comment]
Just use a randomly named temp file to fix the race, I'm pretty sure it's that simple

**Comment by l-j-g** [comment]
isn't that what's happening already? or do you mean each individual process will compile a separate randomly named file?

**Comment by prusnak** [comment]
> or do you mean each individual process will compile a separate randomly named file?

Yes, I think that's what was meant. Attempt to implement the fix is in https://github.com/tinygrad/tinygrad/pull/1458

**Comment by waifairer** [comment]
The best solution for this appears to be to write our own `blobdlopen`, as was provided here:
https://stackoverflow.com/questions/5053664/dlopen-from-memory

The handle for this can be passed into CDLL and it will be used instead of a filesystem call.
