### ISSUE TITLE
JIT with constant folded inputs is broken 

### ISSUE THREAD

**Issue by kunwar31** [tinygrad/tinygrad#1273]
after constant folding was fixed in https://github.com/tinygrad/tinygrad/pull/1227, adding .contiguous() to inputs of JITed functions was suggested as a fix for passing around 1-D tensors as inputs 
but this creates another problem where there is always an extra kernel because of .contiguous() which isn't part of JIT
![image](https://github.com/tinygrad/tinygrad/assets/24824080/cd64218a-ca19-4a95-90d7-286848864d32)

using the example doc method, in foo1 does work but needs to create a 2-D tensor. there should be a better way

**Comment by g1y5x3** [comment]
Which also relates to current CIFAR training speed variation
![image](https://github.com/tinygrad/tinygrad/assets/17937555/644046d5-c3e1-4e08-a86d-3127c2de2742)
![image](https://github.com/tinygrad/tinygrad/assets/17937555/2f160ce2-04a7-4053-beb0-a8bff708566b)
