### ISSUE TITLE
BFloat16 support

### ISSUE THREAD

**Issue by dc-dc-dc** [tinygrad/tinygrad#1290]
LLaMA V2 weights are shipped in bfloat16 which we currently don't support

There is a workaround from [llama.cpp](https://github.com/ggerganov/llama.cpp/blob/294f424554c1599784ac9962462fc39ace92d8a5/convert.py#L338-L341) by converting to float32, but doubles the memory footprint

Backend Support:

- [x] LLVM
- [ ] CUDA
- [ ] OPENCL
- [ ] METAL
- [ ] CLANG
- [ ] NUMPY
- [ ] TORCH

**Comment by kunwar31** [comment]
openCL doesn't support bf16, HIP, CUDA should.

**Comment by kunwar31** [comment]
the workaround can be extended to bf16 --> fp32 --> fp16

**Comment by sekstini** [comment]
If you grab the huggingface ones (-hf suffix) they are in fp16.
I compared them weight by weight and can confirm that the errors between them are tiny [[gist]](https://gist.github.com/sekstini/540bd34141633be05340879fc3a40d05).

I also checked if converting bf16 -> fp16 resulted in noticable losses, but those are negligible as well:
![image](https://github.com/tinygrad/tinygrad/assets/127142660/23476bf8-8ede-4a63-87b3-b0f550966706)

**Comment by dc-dc-dc** [comment]
Looks like its in beta support for [metal](https://developer.apple.com/documentation/metal/mtldatatype/mtldatatypebfloat)

**Comment by wozeparrot** [comment]
It's like half merged in #1293, I think we can leave this open for tracking for some of the other backends.

**Comment by geohot** [comment]
I want this as the generic. Needs bitcast operator support

for bf16 -> float32
`x.bitcast(dtypes.uint16).cast(dtypes.uint32).mul(1<<16).bitcast(dtypes.float32)`
for float32 -> bf16
`x.bitcast(dtypes.uint32).div(1<<16).cast(dtypes.uint16).bitcast(dtypes.bfloat16`

**Comment by prusnak** [comment]
FTR PR https://github.com/tinygrad/tinygrad/pull/1284 implemented conversion of bfloat16 to float16 via LLVM to maximize the number of supported devices:

https://github.com/tinygrad/tinygrad/blob/9d142430cbe61121c864c0015f1de83c94a7d2c0/tinygrad/state.py#L71-L76

**Comment by nullr0ute** [comment]
> openCL doesn't support bf16, HIP, CUDA should, in theory

What about native CPU support for bf16, Intel, Arm and others now implement native bf16 instructions in their CPUs for acceleration.
