### ISSUE TITLE
[Bounty] Training RNN-T

### ISSUE THREAD

**Issue by INF800** [tinygrad/tinygrad#1295]
Hi @geohot, 

I want to take up this task. Please let me know what dataset do you intend me to train the model with.

Best,
Rakesh

**Comment by dosier** [comment]
Bounties can be locked by submitting a draft PR that shows some considerable work in progress.

**Comment by INF800** [comment]
I see some "bounty-locked" tags at https://github.com/tinygrad/tinygrad/issues?q=RNN-T ... Is this issue available for the take ?

**Comment by dosier** [comment]
seems locked #933, tho not in the bounty spreadsheet. @geohot may have to update that.
