### ISSUE TITLE
Negative min/max or rhs in Symbolic

### ISSUE THREAD

**Issue by ronak69** [tinygrad/tinygrad#1316]
Edit: This is actually a minor bug rather than a major issue. I apologize for the false positive.

Symbolic **is** agnostic to div/mod implementation of backends.

> Even though `Variable()` constructor doesn't allow negative `min/max`, still there are
> some bugs in div and mod implementation.
> 
> ### Floor division
> 
> * Two kinds of floor divisions:
>   1. round towards zero (C) `-21//5 => -4.2 => -4`
>   2. round towards negative infinity (Python) `-21//5 => -4.2 => -5`
> 
> * As mod depends on floor division, two mod operations as well.
> 
> * A div expression: `lhs//rhs`
> 
> * These two only differ if **one** of `lhs` or `rhs` operand to div is negative.
>   * `ShapeTracker` doesn't use negative `rhs` values for div and mod.
>   * But `lhs`'s `min/max` can be negative because of negative values in `strides`.
>     Or by using operations like `a-10` or `a*-1` which clearly produce negative
>     `min/max`.
> 
> * So symbolic's output is currently **not** agnostic to the div implementation of
>   a backend (or any program that evaluates the rendered expression).
> 
> * Symbolic should be able to produce output for both kinds of implementations and
>   let backends choose which one it wants. Another option is to select one implementation
>   in symbolic and let backends match/convert their implementation to symbolic's.
> 
> * Yet another option is to make sure users of symbolic never pass negative `lhs` to div or mod.
> 

### Conflicting tests!

* First test expects C like div and second test expects Python like.
* `7//-2` equals `-4` in Python and `-3` in C

https://github.com/tinygrad/tinygrad/blob/9746f6d09412241adb6ce9b64e06cbd0a46e8689/test/unit/test_symbolic.py#L110-L111

* `-90//11` equals `-9` in Python and `-8` in C

https://github.com/tinygrad/tinygrad/blob/9746f6d09412241adb6ce9b64e06cbd0a46e8689/test/unit/test_symbolic.py#L207-L208

> 
> ### Questions
> 
> * What are the exact requirements of the symbolic library?
>   Constraints on `min`, `max` and `rhs`?
> * Which kind of div and mod do each of the backends implement?
>

**Comment by ronak69** [comment]
#1345 fixes this issue as well as the "infinite recursion in mod if negative variables" issue.

**Comment by chenyuxyz** [comment]
no symbolic anymore
