### ISSUE TITLE
Temporary `ContextVar` values

### ISSUE THREAD

**Issue by dosier** [tinygrad/tinygrad#1321]
**Proposal**: add way to temporarily change context var values, e.g. 
```py
with Debugging(level=4, graph=1): // on enter set the context vars to temp values, on exit, change them back
   // some ops
// some other ops we don't care about for the debugging
```
I find myself wanting to debug some specific part of the code sometimes and it'd make it easier to navigate the logs. I saw there is a Context class which supports temporarily adding to the var stack, but that doesn't work if the key already exists in the stack.

**Comment by AlexTelon** [comment]
If you are talking about `tinygrad.helpers.Context` and `tinygrad.helpers.ContextVar` then I think it already works as you describe. At least on master I can run the below code without issue.

```python
from tinygrad.helpers import Context, DEBUG, ContextVar

FOO = ContextVar("FOO", 0)


assert FOO.value == 0
assert DEBUG.value == 0

with Context(FOO=4, DEBUG=1):
    assert FOO.value == 4
    assert DEBUG.value == 1

assert FOO.value == 0
assert DEBUG.value == 0
print('all passed')
```

But again I'm new to tinygrad so I might be missing something important here.

**Comment by dosier** [comment]
> If you are talking about `tinygrad.helpers.Context` and `tinygrad.helpers.ContextVar` then I think it already works as you describe. At least on master I can run the below code without issue.
> 
> ```python
> from tinygrad.helpers import Context, DEBUG, ContextVar
> 
> FOO = ContextVar("FOO", 0)
> 
> 
> assert FOO.value == 0
> assert DEBUG.value == 0
> 
> with Context(FOO=4, DEBUG=1):
>     assert FOO.value == 4
>     assert DEBUG.value == 1
> 
> assert FOO.value == 0
> assert DEBUG.value == 0
> print('all passed')
> ```
> 
> But again I'm new to tinygrad so I might be missing something important here.

Ah yes you are correct there, I think we should probably refactor it to not use a stack lookup at all since its having a bit of a performance cost but that may be for another issue. Also migration of Graph to a context var would be good.
