### ISSUE TITLE
Implement `n_kv_heads` argument for LLaMA-2 Transformer to enable 70B model

### ISSUE THREAD

**Issue by prusnak** [tinygrad/tinygrad#1339]
PR https://github.com/tinygrad/tinygrad/pull/1284 adds LLaMA-2 support, but the 70B model is disabled at this moment:

https://github.com/tinygrad/tinygrad/blob/12dd09ad5406af090cdb5d6ac95a0277bd60a99b/examples/llama.py#L185-L189

To enable it, we need to implement `n_kv_heads` for LLaMA-2.

Upstream implementation: https://github.com/facebookresearch/llama/blob/master/llama/model.py

**Comment by tanmaysachan** [comment]
I'd like to take this up if no one's on it yet
