### ISSUE TITLE
CI is not testing CLANG properly

### ISSUE THREAD

**Issue by chenyuxyz** [tinygrad/tinygrad#1366]
added a always fail test cast to `test_tensor.py` and CI still [passed](https://github.com/chenyuxyz/tinygrad/actions/runs/5691894156). Not sure if it's only for CLANG
```
@unittest.skipUnless(Device.DEFAULT == "CLANG", f"test CLANG")
class TestClang(unittest.TestCase):
  def test_always_fail(self):
    assert False
```

The recent CI time optimization [change](https://github.com/tinygrad/tinygrad/commit/a0965ee1988cb4bfd08e829d4cff1829fa591ff0) might be dropping tests. Also the CI log now is full of warnings like 
`D:\a\tinygrad\tinygrad\test\test_conv.py:6: PytestUnknownMarkWarning: Unknown pytest.mark.exclude_cuda - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
    pytestmark = [pytest.mark.exclude_cuda, pytest.mark.webgpu]`

**Comment by geohot** [comment]
Hmm, this is not good. I read the CI change, but it's hard to test for this. Want to track it down?

**Comment by chenyuxyz** [comment]
Yeah I will fix this before merging any symbolic jit stuff because I broke something and CI did not catch it.

Also clang+ubuntu was dropped from that CI change, was it intended?

**Comment by geohot** [comment]
Yea, it was pretty redundant with clang + windows, I was fine with saving the time. But it shouldn't be skipping tests
