### ISSUE TITLE
Tracking Issue: windows+clang in CI

### ISSUE THREAD

**Issue by wozeparrot** [tinygrad/tinygrad#1377]
Since windows+clang CI was added in #1011, it probably was never actually working correctly, but it was unnoticed due to also having a ubuntu+clang CI, but with the merge of #1252, ubuntu+clang CI was removed and only the broken windows+clang CI remained. This was first noticed in #1366 and temporarily patched around by merging #1368, which brought ubuntu+clang CI back.

Now there has been some work in #1375 which brings a fixed windows+clang CI back to replace the ubuntu+clang CI, but this has found that 26 tests are failing on windows+clang, mainly dtype related ones.

Opening this issue to track progress. You can pull the first commit of #1375 to test in CI.

**Comment by geohot** [comment]
Windows is not a supported platform.
