### ISSUE TITLE
numpy default cast to float64 in some cases

### ISSUE THREAD

**Issue by geohotstan** [tinygrad/tinygrad#1383]
There are several instances where numpy default casts to float64 instead of float32, mainly caused when int32 or int64 are involved.

e.g.
```
ON CPU
In [9]: cmp = Tensor([1, 0], dtype=dtypes.int32) == Tensor([1.1, 1.0], dtype=dtypes.float32)
In [10]: cmp.realize()
KeyError: 'float64'

In [17]: Tensor([1], dtype=dtypes.int32).exp().realize()
KeyError: 'float64'

In [17]: Tensor([1], dtype=dtypes.int32).log().realize()
KeyError: 'float64'

In [38]: Tensor([1], dtype=dtypes.int32).sin().realize()
KeyError: 'float64'

In [4]: Tensor([1], dtype=dtypes.int32).sqrt().realize()
KeyError: 'float64'

There might be more
```

There are no internal ways to change numpy's default casting behavior https://github.com/numpy/numpy/issues/6860

So some possible solutions of covering this issue are:

- change to `UnaryOps.SIN: lambda x: np.sin(x, dtype=np.float32)` (this doesn't seem right cuz what about when x is float16)
- overload/wrap the numpy functions to cast to float32 if float64?
- write a similar promote_types() function that wraps every x or y to cast to float32 if it's int32 or int64 (so ret isn't float64)?
- other

Not sure which solution is proper

**Comment by dc-dc-dc** [comment]
I added in a `match_types` helper function to help with this behavior
Changing `CMPEQ`  to `np.equal(*match_types(x,y))` should resolve the first case

Not sure what the ideal solution would be for the unary ops tho

**Comment by geohotstan** [comment]
update:

`In [38]: Tensor([1], dtype=dtypes.int32).sin().realize()` examples like this on other backends, like METAL, casts to the original dtype, so after realize() this Tensor would still be `dtype=int` with value `[0]`

Not sure if this is a bug or not since 
```
In [5]: torch.tensor([1], dtype=torch.int32).sin().dtype
Out[5]: torch.float32
```

I've tried using [np.min_scalar_type()](https://numpy.org/doc/stable/reference/generated/numpy.min_scalar_type.html) to cast the result of functions like `np.sin()` to smallest size but doing it this way catches the AssertionError:
```
--> 162 assert self.realized.dtype == self.dtype or self.dtype.__class__ is ImageDType, f"dtype mismatch on realize got {self.realized.dtype} expected {self.dtype}"
AssertionError: dtype mismatch on realize got dtypes.half expected dtypes.int
```

a little unsure what's the expected behavior now...

**Comment by geohotstan** [comment]
https://github.com/tinygrad/tinygrad/pull/1525 fixed this by allowing float64 in dtypes
