### ISSUE TITLE
llama on METAL performance regression

### ISSUE THREAD

**Issue by chenyuxyz** [tinygrad/tinygrad#1395]
got `min(ran model time)` ~140 ms on master. I could not find a commit that fully reproduces <100ms from the speedup, but previously I could get ~120ms
bisecting leads to #1335 might be the issue
commit `d4ebadf` before the change gets me ~123ms
commit `bd54105` add the change gets me ~140ms
would be nice if someone can confirm the regression is not just my setup error

tested with command from #1209 on my M1 Max METAL backend
`PYTHONPATH=. python3.11 -O examples/llama.py --prompt "Hello." --count 10 --temperature 0 --timing`

**Comment by wozeparrot** [comment]
maybe we should just revert #1335, cuz #1355 has also been bisected to #1335, and now this as well.

**Comment by geohot** [comment]
Reverted #1335
