### ISSUE TITLE
Performing operations on disk tensors corrupts files

### ISSUE THREAD

**Issue by terafo** [tinygrad/tinygrad#1485]
The simplest example would be something like this. This operation crashes, but not before corrupting the file, loading it the second time fails since file is modified with this.
```python
from tinygrad.state import torch_load
weights = torch_load("whisper-tiny.pt")
(weights["model_state_dict"]["decoder.positional_embedding"]*2).realize()
```
As I see it the pretty simple solution would be to make a flag for Tensor class that makes it readonly, mark disktenros with them and make an assert in realize that crashes program/outputs warning and does nothing on attempt to interact with read-only tensor.
Maybe I'm missing something here and there's a better solution?

**Comment by prusnak** [comment]
I managed to brick my LLaMA weights by experimenting too.

I marked the weights files read-only by using `chmod 444` and had to do the following update to make the loading work again:

``` patch
diff --git a/tinygrad/runtime/ops_disk.py b/tinygrad/runtime/ops_disk.py
index b48c32a..fed37bb 100644
--- a/tinygrad/runtime/ops_disk.py
+++ b/tinygrad/runtime/ops_disk.py
@@ -11,9 +11,9 @@ class RawDiskBuffer(RawBufferMapped):
     self.offset = offset  # this is an offset in bytes
     assert device is not None or buf is not None, "disk tensor needs a path or a buf"
     if device is not None:
-      f = open(device, "a+b")
+      f = open(device, "rb")
       if os.path.getsize(device) < size * dtype.itemsize: os.ftruncate(f.fileno(), size * dtype.itemsize)
-      buf = [f, mmap.mmap(f.fileno(), size * dtype.itemsize), 1]
+      buf = [f, mmap.mmap(f.fileno(), size * dtype.itemsize, prot=mmap.PROT_READ), 1]
     else:
       buf[2] += 1
     # NOTE: we don't call super since disk tensors don't use RAM
```

It's trivial to expand the `__init__` contructor of RawDiskBuffer with `readonly: bool=False` argument which performs the change above when set to `True`. Or would it make sense to make `readonly=True` by default and mark every usage that needs write access explicitly?

**Comment by chenyuxyz** [comment]
closed as stale, disk tensor has been rewritten
