### ISSUE TITLE
fast-apt-mirror is flaky

### ISSUE THREAD

**Issue by roelofvandijk** [tinygrad/tinygrad#1489]
See https://github.com/tinygrad/tinygrad/actions/runs/5798582481/job/15716675813?pr=1474

```
Run vegardit/fast-apt-mirror.sh@v1
Run echo "::group::Linux: Configure fast APT mirror"
Linux: Configure fast APT mirror
  APT::Acquire::Retries "3";
  + curl -sSfL --retry 3 --max-time 6 https://raw.githubusercontent.com/vegardit/fast-apt-mirror.sh/v1/fast-apt-mirror.sh -o /home/runner/fast-apt-mirror.sh
  Current mirror: http://azure.archive.ubuntu.com/ubuntu/ (/etc/apt/sources.list)
  Randomly selecting 20 mirrors...done
  Checking health status of 20 mirrors....................done
   -> 1 mirrors are reachable and up-to-date
  
  Speed testing 1 of the available 1 mirrors (sample download size: 1024KB)done
  ERROR: Could not determine any fast mirror matching required criterias.
  Error: Process completed with exit code 222.
```

I wonder whether it can be removed without a large impact.

**Comment by wozeparrot** [comment]
I originally added this because the azure apt mirror was being flaky, but it seems to just cause more problems.

I filed an issue upstream for one of them.

**Comment by roelofvandijk** [comment]
It also does not seem to be worth it in terms of speedup.

**Comment by wozeparrot** [comment]
The point of it wasn't for speed, it was for CI consistency cuz the azure apt mirror is sometimes flaky.

**Comment by roelofvandijk** [comment]
Crystal.

**Comment by roelofvandijk** [comment]
Azure apt mirror flaking out again https://github.com/tinygrad/tinygrad/actions/runs/6039706674/job/16388972840#step:7:1 @wozeparrot

**Comment by wozeparrot** [comment]
Should probably bring back fast-apt-mirror

**Comment by wozeparrot** [comment]
Actually is there anyway we can cache the apt packages?

**Comment by wozeparrot** [comment]
no longer relevant
