### ISSUE TITLE
Can't create tensor with empty buffer in metal, gpu 

### ISSUE THREAD

**Issue by geohotstan** [tinygrad/tinygrad#1498]
```
# ====== Works ======

In [21]: Tensor([], device="TORCH").realize()
Out[21]: <Tensor <LB (0,) dtypes.float op=buffer<0, dtypes.float> st=ShapeTracker(shape=(0,), views=[View(shape=(0,), strides=(1,), offset=0, mas
k=None, contiguous=True, shape_strides=((0, 1),))])> on TORCH with grad None>

In [28]: Tensor([], device="LLVM").realize()
Out[28]: <Tensor <LB (0,) dtypes.float op=buffer<0, dtypes.float> st=ShapeTracker(shape=(0,), views=[View(shape=(0,), strides=(1,), offset=0, mask=None, contiguous=True, shape_strides=((0, 1),))])> on LLVM with grad None>


# ====== Doesn't Work ======

In [25]: Tensor([], device="GPU").realize()
LogicError: create_buffer failed: INVALID_BUFFER_SIZE

In [26]: Tensor([], device="METAL").realize()
AttributeError: 'NoneType' object has no attribute 'contents'
```

Not sure if this works on CUDA since I don't have nvidiagpu

**Comment by geohotstan** [comment]
I'm trying random shtuff and by adding
`elif size == 0: buf = cl.Buffer(CL.cl_ctxs[int(device)], cl.mem_flags.READ_WRITE, dtype.itemsize)`
to CLBuffer.__init__() fixes the GPU error.
Is this proper pyopencl?????
Does anyone know?

**Comment by ZoneTwelve** [comment]
Because I also want to know what cause the error to happen, so I made an example for testing in my [personal repo](https://github.com/ZoneTwelve/tinygrad/blob/master/examples/create_tensor.py)
If anyone is interested to discuss this issue, please contact me. 

and on CUDA device, the error still exist.
```
DEBUG=4 ./create_tensor.py CUDA
----- CUDA -----
*** exec  0.00 GB    0.04 ms op: UnaryOps.NOOP        out(float): (0,)                           in(1): [(0,)]
Traceback (most recent call last):
  File "tinygrad-zonetwelve/examples/./create_tensor.py", line 12, in <module>
    my_tensor = Tensor([], device=device).realize()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "tinygrad-zonetwelve/tinygrad/tensor.py", line 94, in realize
    self.lazydata.realize()
  File "tinygrad-zonetwelve/tinygrad/lazy.py", line 145, in realize
    elif self.optype is LoadOps: LOAD_OPS_DISPATCHER[cast(LoadOps, self.op.op)](self)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "tinygrad-zonetwelve/tinygrad/lazy.py", line 368, in _realize_from
    buffer.realized = Device[buffer.device].buffer.fromCPU(rawbuf.toCPU(), **buffer._device_extra_args())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "tinygrad-zonetwelve/tinygrad/runtime/lib.py", line 30, in fromCPU
    ret = cls(prod(x.shape), dtypes.from_np(x.dtype), **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "tinygrad-zonetwelve/tinygrad/runtime/ops_cuda.py", line 51, in __init__
    def __init__(self, size, dtype): super().__init__(size, dtype, cuda.mem_alloc(size * dtype.itemsize)) # type: ignore
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pycuda._driver.LogicError: cuMemAlloc failed: invalid argument
```

**Comment by ZoneTwelve** [comment]
I believe we should not create a size 0 Tensor.

**Comment by geohotstan** [comment]
I guess when size == 0 we do `cl.Buffer(CL.cl_ctxs[int(device)], cl.mem_flags.READ_WRITE, dtype.itemsize)` is okay since this matches torch?
```
In [10]: torch.tensor([], dtype=torch.float32).element_size()
Out[10]: 4
```
which is the dtype.itemsize of a float32



> I believe we should not create a size 0 Tensor.

what do you mean? As in there should not be support for 0 shaped tensors or?

**Comment by ZoneTwelve** [comment]
> I guess when size == 0 we do `cl.Buffer(CL.cl_ctxs[int(device)], cl.mem_flags.READ_WRITE, dtype.itemsize)` is okay since this matches torch?
> 
> ```
> In [10]: torch.tensor([], dtype=torch.float32).element_size()
> Out[10]: 4
> ```
> 
> which is the dtype.itemsize of a float32
> 
> > I believe we should not create a size 0 Tensor.
> 
> what do you mean? As in there should not be support for 0 shaped tensors or?

Apologies for any shortcomings in my English.
I mean **I am of the opinion that producing tensors with a size of 0 should be avoided.**

**Comment by wozeparrot** [comment]
There is a distinction between 0 shaped tensors and tensors with 0 size.

**Comment by nimlgen** [comment]
If we wanna allocate device buffer of at least size 1byte to fix the problem, I can handle this with a single line in the coming allocator PR.
