### ISSUE TITLE
'double' is not supported in Metal

### ISSUE THREAD

**Issue by yiminghan** [tinygrad/tinygrad#1548]
`double` is introduced in this PR: https://github.com/tinygrad/tinygrad/pull/1525
but it's not supported by METAL.

It's really easy to get into this state because numpy defaults to double: 

From https://numpy.org/doc/stable/reference/arrays.dtypes.html
```
The default data type: [float_](https://numpy.org/doc/stable/reference/arrays.scalars.html#numpy.float_).
```

For example, sample repro script:

```
from tinygrad.tensor import Tensor
import numpy as np

y = Tensor(np.eye(2))
x = Tensor(np.random.randn(2, 2))
(x @ y).realize()
```

**Comment by yiminghan** [comment]
looks like CLANG is also broken, but that's an easy fix: https://github.com/tinygrad/tinygrad/pull/1549/files

**Comment by dc-dc-dc** [comment]
Metal and WEBGPU do not support double, there should have been an assert in the buffer on creation. Also LLVM should not work either as it will need to downcast the float64 to f32
