### ISSUE TITLE
Float("Nan") == Any number is True

### ISSUE THREAD

**Issue by ZenginU** [tinygrad/tinygrad#1556]
So with the #1493 commit, now Float("NaN") == Any Number is True

Nan == 6 is True, and so on.

```
x = Tensor([float("inf"), float("-inf"),float("nan"), 5,5,-4])
x == 6 is [0. 0. 1. 0. 0. 0.]

```

Note: Not sure about the title, admins can change it to make it more general

**Comment by wozeparrot** [comment]
Probably related: #862

**Comment by geohotstan** [comment]
```
  def __ge__(self, x) -> Tensor: return (((self>float('-inf')) + (self<float('inf')) + (x>float('-inf')) + (x<float('inf'))) < 3).where(0.0, (1.0-(self<x)))
  def __le__(self, x) -> Tensor: return (((self>float('-inf')) + (self<float('inf')) + (x>float('-inf')) + (x<float('inf'))) < 3).where(0.0, (1.0-(self>x)))
  def __ne__(self, x) -> Tensor: return (((self>float('-inf')) + (self<float('inf')) + (x>float('-inf')) + (x<float('inf'))) < 3).where(1.0, ((self<x) + (self>x)))   # type: ignore
  def __eq__(self, x) -> Tensor: return 1.0-(self != x)       # type: ignore
```
shield your eyes from this cursed concoction of code 🫣
but yeah this hack fixes the float('nan') issue for ge, le, ne, and eq
probably not at all ideal

it is also possible to say screw it and totally curse the tensor.py implementation of ge, le, ne, and eq and fix #1562 while at it, but probably not a good idea.

either way this is one possible fix
gonna try to find more

**Comment by gabeorosan** [comment]
Not sure how important, but that runs into issues if both are inf. What about this?
```
  def __ge__(self, x) -> Tensor: return (self>x) + (self==x)
  def __le__(self, x) -> Tensor: return (self<x) + (self==x)
  def __ne__(self, x) -> Tensor: return 1.0 - (self==x)
  def __eq__(self, x) -> Tensor: return (1/((self*x*float('inf')))<1) - (self<x) - (self>x)
```
This is testing as slightly faster that any other workaround for me. You can also divide by zero instead of multiplying by inf but this seems more intuitive/reliable

**Comment by imaolo** [comment]
I think it is impossible to get the correct behavior with only CMPLT, the only comparison op at the moment.

**Comment by chenyuxyz** [comment]
this is fixed on master with CMPEQ

both
```
print((Tensor([float("inf"), float("-inf"),float("nan"), 5,5,-4])==6).numpy())
```
```
print((Tensor([float("inf"), float("-inf"),float("nan"), 5,5,-4])==float("nan")).numpy())
```
return
```
[False False False False False False]
```
