### ISSUE TITLE
LLama: 20% slowdown in the last 2 weeks

### ISSUE THREAD

**Issue by roelofvandijk** [tinygrad/tinygrad#1587]
On my machine, llama has slowed down by 20% with the commits added in the last 2 weeks. I have not investigated this further.
The slowdown might be visible the tests as well, although that's sensitive to newly added tests.

**Comment by geohot** [comment]
$200 bounty if your PR's together bring it back

**Comment by chenyuxyz** [comment]
use #1209 for tracking
