### ISSUE TITLE
Bounty: Training 3D-UNet

### ISSUE THREAD

**Issue by waifairer** [tinygrad/tinygrad#1637]
Add the training logic to examples/mlperf/model_train.py -> def train_unet3d():

[Links](https://github.com/mlcommons/training/tree/master/image_segmentation/pytorch) to the reference implementation for image segmentation.

Training Dataset: [kits19](https://github.com/neheller/kits19).

MLPerf training rules [here](https://github.com/mlcommons/training_policies/blob/master/training_rules.adoc#appendix-allowed-optimizers)

---

Current Bounty: $500
To lock the bounty submit a draft PR with a decent amount of progress made
Make sure to reference this issue in the PR for future tracking

Notice: If the PR goes stale the bounty will be unlocked

**Comment by waifairer** [comment]
Previous attempts:
https://github.com/tinygrad/tinygrad/pull/1469

**Comment by iantimmis** [comment]
Is this bounty for this still available? Looks like previous attempts were closed.
