### ISSUE TITLE
Bounty: Training BERT-large

### ISSUE THREAD

**Issue by waifairer** [tinygrad/tinygrad#1639]
Add the training logic to examples/mlperf/model_train.py -> def train_bert():

Reference implementation: [BERT](https://github.com/mlcommons/training/tree/master/language_model/tensorflow/bert)

Training dataset: [Wikipedia 2020/01/01](https://drive.google.com/drive/folders/1oQF4diVHNPCclykwdvQJw8n_VIWwV0PT)

MLPerf training rules [here](https://github.com/mlcommons/training_policies/blob/master/training_rules.adoc#appendix-allowed-optimizers)

---

Current Bounty: $500
Bounty Locked: #2302

**Comment by MutugiD** [comment]
would love to work on this

**Comment by biniyam69** [comment]
hmm seems interesting

**Comment by ThiagoLeal11** [comment]
Hi everyone,

I'm not sure if anyone else is working on this task, but I've been working on it for a week now. I'm able to train the model, but I'm still fixing some convergence issues and optimizing the performance. I'll open a PR as soon as I have the trained weights.
