### ISSUE TITLE
Remove the runtime imports from lazy.py

### ISSUE THREAD

**Issue by geohot** [tinygrad/tinygrad#1653]

**Comment by wozeparrot** [comment]
Basically `_realize_from` and some of the other functions should have the `if`s in them that change behaviour based on what runtime the buffer is from, it should just be generic instead.

**Comment by varshneydevansh** [comment]
I would love to work on this. =)

**Comment by kwkr** [comment]
@geohot @wozeparrot Is this issue still relevant given the recent changes to the `lazy.py`? The only imports are `RawBuffer`, which is only used as a type and `RawNumpyBuffer.fromCPU` on line 202.

**Comment by adirsingh96** [comment]
is this still open?
