### ISSUE TITLE
Docment the release roadmap/cycle and process

### ISSUE THREAD

**Issue by nullr0ute** [tinygrad/tinygrad#1658]
It's not clear from generally just looking about if there's a release cycle or roadmap process, how often and why a release is tagged. Is it date based, feature based or just randomly? A lot of users will download a tagged release on the assumption that is a good point in time to consume the code so it would be useful to document how/when those tags are created to set user's expectations.

**Comment by wozeparrot** [comment]
As of right now, the installation instructions on the README do say to install from source.

**Comment by wozeparrot** [comment]
Probably gonna tag 0.7 sometime this week. The releases are kinda just random for now, until tinygrad API is somewhat stable at least, everything changes too much right now.
