### ISSUE TITLE
Classmethods instead of staticmethods

### ISSUE THREAD

**Issue by yochem** [tinygrad/tinygrad#1695]
I noticed that many methods of the Tensor class are marked as static methods, even though they return new Tensor instances. These methods seem more like class methods than static methods. Converting them to class methods would:

1. Make it more clear that those methods create new Tensors
2. Will support subclassing Tensor

Is there any reason they are currently static methods? If there are no arguments against changing those static methods to class methods, I can create a PR for it.

**Comment by geohot** [comment]
Agreed classmethod is probably more correct.

**Comment by yochem** [comment]
Will change it. Can i also add the type hint `typing.Self` to these methods? I think that would require python v3.11.

**Comment by yochem** [comment]
seems like 3.11 is already required? https://github.com/tinygrad/tinygrad/pull/1584#issuecomment-1685362557

**Comment by wozeparrot** [comment]
https://github.com/tinygrad/tinygrad/pull/1716#issuecomment-1703082648
