### ISSUE TITLE
Disk tensor fails to cast to float16

### ISSUE THREAD

**Issue by gijskoning** [tinygrad/tinygrad#1767]
Casting [0,1,2,3] to float16 results in [0.   , 0.   , 0.   , 1.875]

I haven't yet found the source of the problem. Any ideas?

See failed test: https://github.com/tinygrad/tinygrad/commit/41dace7fa8e1692e7f5805b98e438f11f3535093

**Comment by geohot** [comment]
You don't understand what disk tensor casting does.
