### ISSUE TITLE
Fix VALIDHACKS for Images and make it default ($300 bounty)

### ISSUE THREAD

**Issue by geohot** [tinygrad/tinygrad#1801]
When you read images out of bounds, they will return 0s. Currently the compiler is unaware of this and still gates the load. Figure out when we don't need it and disable it.

Images are used in the openpilot model `openpilot/go.sh` that have this extra gated load. Safely remove it!

Must be well tested for bounty, it's easy to do this subtly wrong.

Simple example of issue:
`GPU=1 DEBUG=4 FORWARD_ONLY=1 IMAGE=2 python3 test/test_ops.py TestOps.test_simple_padding_conv2d`

generates 

`float4 val0 = ((((lidx0*(-1))<0)*(lidx0<3)))?(read_imagef(data1, smp, (int2)(((lidx0+1)%2),(((lidx0+1)/2)+(-1))))):(float4)(0.0f,0.0f,0.0f,0.0f); # (lidx0 ranges from 0-3)`

instead of

`float4 val0 = read_imagef(data1, smp, (int2)(lidx0-1,0))`

to read image

`dtypes.imagef((1, 2, 4)) # the last 4 is the float4, this is a 2x1 image`

That gate is not needed if you remove the `%2` and subtract 2 from the index. You also then don't need the y index at all.

See `validhacks` in `to_image_idx` for the old (broken) code that hacked this. The symbolic engine should be good enough now to do this properly.

**Comment by geohot** [comment]
If you'd like some help from GPT-4 to understand this:

https://chat.openai.com/share/43adae1d-73d6-4d9f-994f-889be7184aec

**Comment by gijskoning** [comment]
I was just experimenting with the test_simple_padding_conv2d test and noticed that there is a max operation that is performed on two equal constants, at least to my understanding. Since this might be optimized I think it is useful to know. I couldn't find something in lazy.py to optimize it. The following output is obtained with forward_pass=1.
```
__kernel void E_4_3(__global float* data0, const __global float* data1, const __global float* data2) {
float val0 = data1[0];
float val1 = data1[1];
float val2 = data2[0];
float alu0 = max(0.0f,0.0f);
*((__global float4*)(data0+0)) = (float4)(float4)(alu0,alu0,alu0,alu0);
*((__global float4*)(data0+4)) = (float4)(float4)(alu0,max((val0*val2),0.0f),max((val1*val2),0.0f),alu0);
*((__global float4*)(data0+8)) = (float4)(float4)(alu0,alu0,alu0,alu0);
}
```
