### ISSUE TITLE
"examples" vs ... supported models

### ISSUE THREAD

**Issue by earonesty** [tinygrad/tinygrad#1804]
i feel like the way ai work will increasingly happen will be more about refinement, integration and use of well-known and tested models and less about the building of brand-new models (which will be larger coordinated efforts, community or otherwise)

and over time, tinygrad should *hopefully* ossify into a battle-tested library suitable for any accelerator and any model with a completely different release schedule than the "examples"

considering that future, the "examples" folder feels like it should be another repo... any maybe even no longer called "examples" - a community maintained set of well-known and heavily used models that are optimized for use with tinygrad

**Comment by geohot** [comment]
Not an issue. After you've contributed to tinygrad a bit and gotten a feel for it I'll entertain things like this.

**Comment by wozeparrot** [comment]
Also, github discussions exist for a reason for stuff like this to not clog the issue tracker
