### ISSUE TITLE
Separate code generation from code execution

### ISSUE THREAD

**Issue by geohot** [tinygrad/tinygrad#1812]
TVM does a great job of this. It's really hard to get tinygrad to output code without running it, and it shouldn't be.

A couple of notes:
* LazyOps should probably only have LazyOps as sources. We can create a LOAD LazyOp to fetch from buffers (which contains the buffers shapetracker, but not the buffer itself). The STORE LazyOp is implied by being the parent. Then this LazyOp determines the compute without containing the buffers.
* MovementOps are already tracked in the ShapeTracker. While the code to keep them around is nice, particularly for Interpreted buffers, it's probably better to just directly apply them. This will save 50 lines of code. Then interpreted buffers can either have an apply shapetracker function or just directly apply them also.
  * This is a massive change. What do you do with MovementOps on the output?
  * This will also make tinygrad a lot faster and I think removes almost all complexity from lazy.py
  * The apply shapetracker function can be completely generic and it generates the minimum MovementOps for a ShapeTracker. Maybe this is the first change to make, can this be recovered?
* Remove ReduceOps and allow them to be any Binary or TernaryOp (ADD, MUL, MAX, MULACC)
  * This would allow prefusion of MUL+SUM, but it might not be worth it
* Remove interpreted altogether? Or just make them not lazy as in teenygrad? I think I like this best, but we'd need MULACC at least
* Alternatively, switch InterpretedOps to as_strided. This will both reduce code and increase speed

**Comment by geohot** [comment]
LazyBuffer should be LazyBuffer/LazyView...the LazyBuffer is always contiguous?

**Comment by DKormann** [comment]
So I am trying to understand the planned refactor this is what I got so far:

    LazyBuffer contains a LazyRawbuffer and a ShapeTracker
    LazyRawbuffer is agnostic to reshape just cares about the computation
    LazyRawBuffer has a LazyOp that defines its computation
    LazyOp has other LazyOps as sources
    A LOAD LazyOp contains a ShapeTracker and another source LazyOp
    In the end the STORE LazyOp has represents the input data we want to execute on

    advantages:

        backend code could be generated without even knowing the data.
        MovementOps can travel up and down the AST
        Right now If you want to do calculation -> Reshape -> Calculation you have a LazyBuffer in the AST that means the you cant put the whole ast in one kernel
        but wth this refactor can you put the whole ast in one kernel?

**Comment by geohot** [comment]
Done, in a much cleaner way! See `LazyBuffer.schedule`
