### ISSUE TITLE
Use github.com/apssouza22/chatflow as a conversational layer. It would enable actual API requests to be carried out from natural language inputs.

### ISSUE THREAD

**Issue by GiovanniSmokes** [tinygrad/tinygrad#1914]
Adding a conversational UI to tinygrad would enable people to 'talk' directly with the tinygrad backend and API requests to be carried out more effectively. RAG can help with some of the problems function calling by language models face at the moment.

https://youtu.be/r3cegH2kviQ

I'm trying to accelerate the adoption of natural language interfaces.

**Comment by wozeparrot** [comment]
This issue tracker isn't the place for this.

**Comment by GiovanniSmokes** [comment]
> The issue tracker isn't the place for this.

Where is the best place to request something like this?
