### ISSUE TITLE
TestEnd2End.test_conv_mnist issue on METAL (tensor cores?)

### ISSUE THREAD

**Issue by geohot** [tinygrad/tinygrad#1967]
`METAL=1 python3 test/models/test_end2end.py TestEnd2End.test_conv_mnist`

is failing

`TC=0 METAL=1 python3 test/models/test_end2end.py TestEnd2End.test_conv_mnist` works, so does `TC=2`

**Comment by geohot** [comment]
Fixed with https://github.com/tinygrad/tinygrad/commit/88b6ed6945df2183e41ec5bd31a78d0637f4c78f

But the issue stands.

**Comment by chenyuxyz** [comment]
stale
