### ISSUE TITLE
CIFAR memory usage broken

### ISSUE THREAD

**Issue by kunwar31** [tinygrad/tinygrad#1989]
Running on RTX 3060 Mobile with 6 gig VRAM
```EVAL_BS=50 BS=128 python examples/hlb_cifar10.py```
It reports around  1.74 GB used, but its using much more 
```781   83.19 ms run,    3.17 ms python,   80.01 ms CL,  570.95 loss, 0.001035 LR, 1.74 GB used,   2027.94 GFLOPS```
Looking at vram usage externally I see it at 4670MiB with occasional spikes
![image](https://github.com/tinygrad/tinygrad/assets/24824080/790428b9-b6bc-4918-9f2f-c922db8dc057)
That one spike after step 781 eventually causes a crash
```pyopencl._cl.MemoryError: clEnqueueMapBuffer failed: MEM_OBJECT_ALLOCATION_FAILURE```

**Comment by geohot** [comment]
I want to delete all the caching allocators in favor of the JIT + Schedule
