### ISSUE TITLE
No module named 'models' when trying to run examples/compile_efficientnet.py

### ISSUE THREAD

**Issue by mikolysz** [tinygrad/tinygrad#2031]
When trying to run:
```
python3 examples/compile_efficientnet.py
```

The following output is returned:
```
File "/Users/miki/code/tinygrad/examples/compile_efficientnet.py", line 2, in
<module>
    from models.efficientnet import EfficientNet
ModuleNotFoundError: No module named 'models'
```

Tinygrad is installed from source as recommended in the readme, the behavior doesn't change whether the working directory is `tinygrad` or `examples`.

**Comment by wozeparrot** [comment]
Can you try with `PYTHONPATH=. python3 examples/compile_efficientnet.py`

**Comment by J4e6eR** [comment]
Try adding these lines before the starting of the code
```python
import sys
from pathlib import Path
sys.path.append(str(Path(__file__).parent.parent))
```
The number of time you write the parent will determine which path you want to add to the system.
This is the path python would look for if they won't find a module.
Generally it's better to append the root director of the repo as a sys path to access all the modules from the repo.

**Comment by wozeparrot** [comment]
@mikolysz This still an issue for you?

**Comment by hmih** [comment]
@mikolysz It is something related to your PYTHONPATH, can you try this installation:

```shell
git clone https://github.com/tinygrad/tinygrad.git
cd tinygrad
python3 -m venv venv
. venv/bin/activate         # do not forget the dot!
python3 -m pip install -e . # do not forget the dot!
```
