### ISSUE TITLE
Winograd GFLOPS GB/s are wrong

### ISSUE THREAD

**Issue by geohot** [tinygrad/tinygrad#2114]
`***    6 E_16384_2_8_8_6_6n2                   arg   2 sz [16384, 1, 1]      [8, 8, 2]    OPs  68174M/   1.65G  mem  0.93 GB tm    460.09us/     0.91ms (148177.44 GFLOPS, 4740.51 GB/s)`

Use the Uops to get this

**Comment by chenyuxyz** [comment]
#3373
