### ISSUE TITLE
JIT: Incorrect output for delayed CPU copy.

### ISSUE THREAD

**Issue by imaolo** [tinygrad/tinygrad#2417]
```
from tinygrad.tensor import Tensor
from tinygrad.jit import TinyJit

@TinyJit
def do_jit(x) -> Tensor: return x.sum().realize()

res = []
res.append(do_jit(Tensor([1]*2)))
res.append(do_jit(Tensor([2]*2)))
res.append(do_jit(Tensor([3]*2)))

print([r.numpy() for r in res])
```
[array(2., dtype=float32), array(6., dtype=float32), array(6., dtype=float32)]

**Comment by imaolo** [comment]
The toCPU() copy is too late. The device buffers have already been written. More reason for a #2391 fix.

**Comment by imaolo** [comment]
Thinking this problem is deeper than removing the toCPU() copy. The jit is returning the same Tensor for each invocation.

**Comment by wozeparrot** [comment]
I'm not sure which behaviour is supposed to be the correct one here, I've been going off the basis that JIT is dumb and just replays the kernels, so if I want the data later then it shouldn't be kept as a tensor. But that makes the user facing behaviour slightly strange. 

An easy-ish fix for this would be to just recreate all output tensors when jitted functions are run, and replace all the output buffers with the new ones, like its done for the input buffers.
But, I'm not sure if this is a potential perf hit/behaviour that we want.

**Comment by imaolo** [comment]
Agreed that the behavior is a bit strange.

For most cases, I had a cheap solution for removing the toCPU() copy. Reallocate _buf, but that is horrible practice, not to mention memory leaks. It would be better to replace at the RawBuffer layer. The issue was replacing the lazybuffer's reference to the RawBuffer that is being replaced, but your comparison to the input buffer mechanism will help a lot with this.

At that point, it might make sense to replace at the Tensor layer, solving the current issue.

Thank you for the suggestions.

**Comment by chenyuxyz** [comment]
supported with Tensor.clone
