### ISSUE TITLE
`np.copy()` doesn't transfer data to CPU

### ISSUE THREAD

**Issue by jaxs-ribs** [tinygrad/tinygrad#2440]
When running the provided code on an M1 or M2 Mac using the Metal backend, attempting to serialize a Numpy array results in the following error:

```
from tinygrad.ops import Device
from tinygrad.tensor import Tensor
import numpy as np
import pickle

print(f"using {Device.DEFAULT} backend") # Metal Backend

output = Tensor.ones((1, 3, 4096)).realize().numpy()
new = np.copy(output)
serialized = pickle.dumps(new)
```

Yields 

```
serialized = pickle.dumps(new)
TypeError: Cannot pickle Objective-C objects
```

The Numpy array should be successfully serialized without encountering a "Cannot pickle Objective-C objects" error, as it is intended to be moved to the CPU.

**Comment by geohot** [comment]
Err, so that's not the problem, the problem is how I scam to not GC the metal object

**Comment by geohot** [comment]
Fixed here, will merge if tests pass https://github.com/tinygrad/tinygrad/pull/2441/files
