### ISSUE TITLE
Getting started issue

### ISSUE THREAD

**Issue by bojanbabic** [tinygrad/tinygrad#2509]
When I run sample code from [Quick Start](https://github.com/tinygrad/tinygrad#quick-example-comparing-to-pytorch) I get the following error:
```
AssertionError: Error Domain=MTLLibraryErrorDomain Code=1 "Invalid library file" UserInfo={NSLocalizedDescription=Invalid library file}

```

**Comment by wozeparrot** [comment]
Duplicate of #2226
