### ISSUE TITLE
where are the model weights saved to?

### ISSUE THREAD

**Issue by m000lie** [tinygrad/tinygrad#2551]
> examples/stable_diffusion.py:591
pytorch loads in the model weights from [hugginface](https://huggingface.co/CompVis/stable-diffusion-v-1-4-original/resolve/main/sd-v1-4.ckpt). where is the file saved? i can't find it anywhere in any of the folders.

**Comment by geohot** [comment]
~/.cache/tinygrad/downloads

**Comment by m000lie** [comment]
hey it's actually stored in `~/Library/Caches/tinygrad/downloads` for me on macOS. just found it. thanks for the guide

**Comment by m000lie** [comment]
`tinygrad/helpers.py`:200 
`_cache_dir: str = getenv("XDG_CACHE_HOME", os.path.expanduser("~/Library/Caches" if OSX else "~/.cache"))`

~/.cache for Windows/Linux
~/Library/Caches for Mac 

Leaving here for future users who have the same question
