### ISSUE TITLE
Bad performance scaling on CPU 

### ISSUE THREAD

**Issue by ThoenigAdrian** [tinygrad/tinygrad#2566]
When using bigger networks on the CPU the amount of time it takes to compute a forward pass doesn't scale with the amount of required computation.

When doubling the layer size around 4x more computation needs to be done. 

However when going from shape=[98, 4096, 4096, 8] to shape=[98, 8192, 8192, 8] it takes 14x more time.

CPU: AMD Epyc 7743P: (CPU=1 environment variable)

| Shape                    | Forward Latency (ms) | Actual Slowdon | Expected Slowdon |
|--------------------------|----------------------|-----------------|-------------------|
| [98, 1024, 1024, 8]      | 15.00                | -               | -                 |
| [98, 2048, 2048, 8]      | 96.02                | 6.4x            | 4x                |
| [98, 4096, 4096, 8]      | 249.06               | 2.5x            | 4x                |
| [98, 8192, 8192, 8]      | 3492.38              | **14x**             | 4x                |
| [98, 16384, 16384, 8]    | 15019.52             | 4.28x           | 4x                |

GPU: RTX 3080 Ti
| Shape                    | Forward Latency (ms) | Actual Slowdon | Expected Slowdon |
|--------------------------|----------------------|-----------------|-------------------|
| [98, 1024, 1024, 8]      | 40.01                | -               | -                 |
| [98, 2048, 2048, 8]      | 44.01                | 1.1x             | 4x          |
| [98, 4096, 4096, 8]      | 81.02                | 2x               |4x                 |
| [98, 8192, 8192, 8]      | 236.06               | 2.91x               | 4x                 |
| [98, 16384, 16384, 8]    | 847.76               | 3.6x              | 4x                 |

Test script:
```python
import time
from tinygrad.tensor import Tensor


class LinearNet:
    def __init__(self, shape):
        self.layers = []
        for i in range(len(shape)-1):
            self.layers.append(Tensor.kaiming_uniform(shape[i], shape[i+1]))

    def __call__(self, x: Tensor) -> Tensor:
        for layer in self.layers:
            x = x.dot(layer)
        return x


def main():
    shapes = [
        [98, 1024, 1024, 8],
        [98, 2048, 2048, 8],
        [98, 4096, 4096, 8],
        [98, 8192, 8192, 8],
        [98, 16384, 16384, 8],
    ]

    for shape in shapes:
        net = LinearNet(shape)
        number_examples = 8
        x = Tensor.rand(number_examples, shape[0], requires_grad=False)
        # measure time of forward pass
        current_time_ns = time.time_ns()
        net(x).realize()
        after_realize_time_ns = time.time_ns()
        print(f"{shape=} forward latency: {(after_realize_time_ns - current_time_ns) / 1_000_000:.2f} ms")


if __name__ == "__main__":
    main()

```

Original Output:
shape=[98, 1024, 1024, 8]     forward latency: 15.00 ms 
shape=[98, 2048, 2048, 8]     forward latency: 96.02 ms 
shape=[98, 4096, 4096, 8]     forward latency: 249.06 ms
shape=[98, 8192, 8192, 8]     forward latency: 3492.38 ms 
shape=[98, 16384, 16384, 8] forward latency: 15019.52 ms 

GPU: RTX 3080Ti (CPU=0 environment variable)
shape=[98, 1024, 1024, 8] forward latency: 40.01 ms
shape=[98, 2048, 2048, 8] forward latency: 44.01 ms
shape=[98, 4096, 4096, 8] forward latency: 81.02 ms
shape=[98, 8192, 8192, 8] forward latency: 236.06 ms
shape=[98, 16384, 16384, 8] forward latency: 847.76 ms

**Comment by alexjtaylor** [comment]
@ThoenigAdrian FWIW I didn't observe the same CPU behavior on my 2020 M1 macbook air:

shape=[98, 1024, 1024, 8] forward latency: 33.00 ms
shape=[98, 2048, 2048, 8] forward latency: 35.48 ms
shape=[98, 4096, 4096, 8] forward latency: 69.76 ms
shape=[98, 8192, 8192, 8] forward latency: 238.41 ms
shape=[98, 16384, 16384, 8] forward latency: 920.38 ms

**Comment by AIBoticsGmbH** [comment]
@alexjtaylor ok thx , good to know 👍  So at least it's not a general issue.

**Comment by ThoenigAdrian** [comment]
@alexjtaylor  ok thx, good to know 👍 . So at least it's not a general issue.

**Comment by han-minhee** [comment]
Could you check the stats when running the script using the CPU?

perf stat -e cache-references,cache-misses python your_script.py

**Comment by ThoenigAdrian** [comment]
@han-minhee  Sry I can't since I'm working on windows

**Comment by chenyuxyz** [comment]
closing as stale, CPU backend was removed
