### ISSUE TITLE
TTS in examples/conversation.py buffer reuse bug on M1 Air

### ISSUE THREAD

**Issue by grantslatton** [tinygrad/tinygrad#2576]
### System info

```@Grants-MacBook-Air tinygrad % uname -a
Darwin Grants-MacBook-Air.local 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:19 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8103 arm64

@Grants-MacBook-Air tinygrad % python3 --version
Python 3.11.4

@Grants-MacBook-Air tinygrad % sysctl -n machdep.cpu.brand_string
Apple M1

@Grants-MacBook-Air tinygrad % sysctl hw.memsize
hw.memsize: 17179869184
```

### Bug

I'm getting an issue with examples/conversation.py

The text to synthesize is getting correctly passed in to the `tts` function (verified with `print` statement). I believe the audio is getting correctly generated for that text, because the length of the clip lines up with the length of the text generated.

But then the audio buffer from the last TTS JIT example, "I am capable of doing a lot of things" gets re-used, but clipped to the length of the clip above

#### Example
If I ask "What's your name" and the LLM says "Stacy", it generates a short clip, but then says "I am capab--"
But if I ask "What do you like to do?" it generates a long clip, and then says "I am capable of doing a lot of things <random noise buzzing because the clip exceeds the JIT example clip>"

Makes me think there is some buffer getting reused, or not overwritten when it's supposed to.

### Hack fix

Running with `GPU=1` fixes the issue, but the program is much, much slower.

**Comment by wozeparrot** [comment]
Can you try with `JIT=2` just to see if its the graph executor?

**Comment by grantslatton** [comment]
`JIT=2` fixes the problem

**Comment by nimlgen** [comment]
@grantslatton can you check on the master now? It's seems to work fine after several metal graph fixes.

**Comment by grantslatton** [comment]
I just pulled and checked and am getting the same bug still.

**Comment by grantslatton** [comment]
@nimlgen I just pulled and checked but am still getting the same bug.

**Comment by geohot** [comment]
JIT=2 bypasses the metal graph executor and runs the kernels one at a time.

**Comment by grantslatton** [comment]
Just pulled master and this bug appears to be fixed, resolving
