### ISSUE TITLE
Remove numpy

### ISSUE THREAD

**Issue by geohot** [tinygrad/tinygrad#2649]
- [ ] Remove numpy from the dtypes
- [ ] Support Tensor creation from lists and nested lists without bumpy
- [ ] Add some clean method to get the Tensor out as a native Python object

Do these before just replacing numpy in places

**Comment by geohot** [comment]
Added the method `.data()` to return a memoryview. That should work without numpy https://github.com/tinygrad/tinygrad/pull/2657

**Comment by IvanVnucec** [comment]
@geohot Can you explain what does it mean to "get the Tensor out as a native Python object"? Example would do.

**Comment by hristog** [comment]
> @geohot Can you explain what does it mean to "get the Tensor out as a native Python object"? Example would do.

This is a good question!
I'm not from the maintainers team (and I could be wrong in saying the following), but my interpretation is that the desired result is a native Python data structure, such as the efficient [`array`](https://docs.python.org/3/library/array.html) type or a newly-introduced `class` equivalent - abstraction-level-wise - to a Numpy `ndarray`, or (I suppose less likely) a plain `list`.

**Comment by hristog** [comment]
For instance, the approach in https://github.com/tinygrad/tinygrad/pull/2745 proposes utilising the standard library `struct.pack`.

**Comment by chenyuxyz** [comment]
dup to #321
