### ISSUE TITLE
Support for NVIDIA Unified Virtual Memory

### ISSUE THREAD

**Issue by nick008a** [tinygrad/tinygrad#2692]
Support NVIDIA Unified Virtual Memory and allow to use RAM when there is not enough GPU memory.

The NVIDIA UVM technology allows to use RAM when the GPU memory is not enough to allocate, I believe this is helpful for those who want to train heavy model on limited GPU memory. The Tensorflow has already support UVM by setting per_process_gpu_memory_fraction bigger than 1, by the way.

**Comment by geohot** [comment]
PCI-E is too slow to do anything practical.
