### ISSUE TITLE
Bug in shapetracker reshape (mask)

### ISSUE THREAD

**Issue by geohot** [tinygrad/tinygrad#2844]
seed=42
st.permute( (1, 2, 0) )
st.pad( ((0, 0), (2, 2), (0, 0)) )
st.reshape( (4, 6, 5, 1) )
st.pad( ((1, 2), (0, 0), (0, 0), (0, 0)) )
st.reshape( (7, 3, 2, 5, 1) )
st.reshape( (7, 6, 5, 1) )
st.reshape( (7, 6, 1, 5, 1) )
st.reshape( (7, 1, 6, 1, 5, 1) )
EXP: ShapeTracker(views=(View(shape=(5, 4, 2), strides=(8, 2, 1), offset=0, mask=None, contiguous=True),))
GOT: ShapeTracker(views=(View(shape=(5, 4, 2), strides=(8, 2, 1), offset=-2, mask=None, contiguous=False),))
****

seed=44
st.permute( (1, 0, 2) )
st.reshape( (2, 10, 1, 5) )
st.reshape( (2, 10, 5) )
st.pad( ((2, 2), (0, 0), (0, 0)) )
st.pad( ((0, 0), (0, 0), (2, 0)) )
st.reshape( (3, 2, 10, 7) )
st.reshape( (3, 2, 10, 7, 1) )
st.reshape( (6, 10, 7, 1) )
EXP: ShapeTracker(views=(View(shape=(10, 2, 5), strides=(10, 5, 1), offset=0, mask=None, contiguous=True),))
GOT: ShapeTracker(views=(View(shape=(10, 2, 5), strides=(10, 5, 1), offset=-10, mask=None, contiguous=False),))
****

simple examples

st.pad( ((2, 0), (0, 0), (0, 0)) )
st.reshape( (2, 2, 5, 5) )
st.reshape( (4, 5, 5) )
EXP: ShapeTracker(views=(View(shape=(2, 5, 5), strides=(25, 5, 1), offset=0, mask=None, contiguous=True),))
GOT: ShapeTracker(views=(View(shape=(2, 5, 5), strides=(25, 5, 1), offset=-50, mask=None, contiguous=False),))
****

st.pad( ((0, 0), (0, 0), (2, 2)) )
st.reshape( (1, 2, 3, 2) )
st.reshape( (1, 2, 6) )
EXP: ShapeTracker(views=(View(shape=(1, 2, 2), strides=(0, 2, 1), offset=0, mask=None, contiguous=True),))
GOT: ShapeTracker(views=(View(shape=(1, 2, 2), strides=(0, 2, 1), offset=-2, mask=None, contiguous=False),))
****

**Comment by geohot** [comment]
x = a.pad( ((2, 0), (0, 0)) )
    x = x.reshape( (2, 2, 5) )
    x = x.reshape( (4, 5) )

**Comment by chenyuxyz** [comment]
fix #2877
