### ISSUE TITLE
Add torch.rot90 to Tensor object

### ISSUE THREAD

**Issue by elizkhel** [tinygrad/tinygrad#2864]
https://pytorch.org/docs/stable/generated/torch.rot90.html

**Comment by geohotstan** [comment]
I think this is just some combination of permute and flip
go give it a try :D

**Comment by elizkhel** [comment]
Oh, sorry for this, I am bit new and finding some troubles.

**Comment by Isalia20** [comment]
It's a matter of flips and transposes depending on parameter k(number of time to rotate), I can add this one if needed

**Comment by geohotstan** [comment]
We're close triggering geohot's siren again
so idk if adding extra api is a good idea atm
https://github.com/tinygrad/tinygrad?tab=readme-ov-file#contributing
see **Features**

**Comment by elizkhel** [comment]
I got it working after some trial and error
