### ISSUE TITLE
AttributeError: 'TinyJit' object has no attribute 'reset'

### ISSUE THREAD

**Issue by wjessup** [tinygrad/tinygrad#2943]
https://github.com/tinygrad/tinygrad/blob/50f2e31d26f6af504cf01ce68054444c80fe8eb7/examples/beautiful_cartpole.py#L74

**Comment by cmstoddard** [comment]
Hey @wjessup I think if you `get pull` the `master` branch, your issue will be fixed.

**Comment by chenyuxyz** [comment]
Tested master and it works fine. Closing as complete.
