### ISSUE TITLE
`cat` with interpreted backends

### ISSUE THREAD

**Issue by g1y5x3** [tinygrad/tinygrad#3094]
Here is a minimum example to reproduce. And probably is happening on TORCH backend as well. But the weird part is that if you run it twice, it works.
![image](https://github.com/tinygrad/tinygrad/assets/17937555/dca2084d-83b9-43b7-96b9-ada277075573)

**Comment by g1y5x3** [comment]
```
from tinygrad import Tensor
X = Tensor.zeros(1,32,4,32)
print(X.realize())
X1 = X.shrink((None, (0,0), None, None))
print(X1.realize())
Y = Tensor.zeros(1,1,4,32)
X2 = X1.cat(Y, dim=1)
print(X2.realize())
```

**Comment by g1y5x3** [comment]
just need to manually make a case when its 0 for llama attention module

**Comment by chenyuxyz** [comment]
the real issue seems to be `AS_STRIDED` cannot be applied to const
