### ISSUE TITLE
maximum autocasts float16 to float32

### ISSUE THREAD

**Issue by geohotstan** [tinygrad/tinygrad#3186]
tiny
```
In [3]: Tensor([1.,2.], dtype=dtypes.half).maximum(3.1).dtype
Out[3]: dtypes.float
```

jax
```
In [6]: jnp.maximum(jnp.array([1., 2.], dtype=jnp.float16), 3.1).dtype
Out[6]: dtype('float16')
```

found this from onnx openpilot implicitly casting float16 to float32 from a Clip op :D

**Comment by chenyuxyz** [comment]
yea it's due to the mid point handling https://github.com/tinygrad/tinygrad/blob/fb4bd2a57d8c4eddacd10f1de16d44451b6c40ca/tinygrad/tensor.py#L842

it also has overflow issue. i think changing it to self/2 + x/2 can fix both issue

**Comment by geohotstan** [comment]
I think particular problem seems to be little less involved
this one might just be cuz `3.1` when `broadcasted` gets set to `default_float`
and `where` then upcasts it to `float32`


```
In [4]: Tensor([1.,2.], dtype=dtypes.half).maximum(Tensor(3.1, dtype=dtypes.half)).dtype
Out[4]: dtypes.half
```

**Comment by chenyuxyz** [comment]
oh i see, we might want to so the same float check for other elementwise op then. t + 3.1 would have same float dtype for t for example
