### ISSUE TITLE
Remove dependence on numpy

### ISSUE THREAD

**Issue by geohot** [tinygrad/tinygrad#321]
With llops, we should be able to write something fast in C to replace them.

**Comment by Runkli** [comment]
do you have anything specific in mind for how shapes should be handled? contiguous array with implicit shape/stride parameter? a default [batch_size, height, width, in_channels] shape assumption?

**Comment by geohot** [comment]
See discussion in "improvements"

**Comment by alat-rights** [comment]
Link: https://github.com/geohot/tinygrad/issues/326
