### ISSUE TITLE
sum from expand backwards does not accumulate in fp32

### ISSUE THREAD

**Issue by chaosagent** [tinygrad/tinygrad#3331]
if you write t.expand(), the backwards is sum(), but if t is fp16, then the sum will be in fp16 and may not have a good time.

need to measure how much this matters in real-world training, but gradients should not have large norm and might just be OK.

you can get around this by writing `def expand(self, ...): return self.cast(acc_dtype).expand(...).cast(self.dtype)` (and #3319 will swap expand and the second cast!)

**Comment by chenyuxyz** [comment]
fix in #4149
