### ISSUE TITLE
HIP Memory access fault after many steps

### ISSUE THREAD

**Issue by chaosagent** [tinygrad/tinygrad#3343]
After training many steps of resnet, the process crashes with:

`Memory access fault by GPU node-1 (Agent handle: 0x561401550ed0) on address 0x7f8942626000. Reason: Page not present or supervisor privilege.`

Everything should be in static jit buffers except the dataloading.

**Comment by chenyuxyz** [comment]
multi or single gpu?

**Comment by chaosagent** [comment]
both, happens faster on multi than single afaict

**Comment by geohot** [comment]
Perhaps #3364 fixes it.

**Comment by chaosagent** [comment]
I think this is fixed by #3364 . Will reopen if I run into it again
