### ISSUE TITLE
Publishing research using tinygrad

### ISSUE THREAD

**Issue by SamRaymond** [tinygrad/tinygrad#3433]
Not sure if this is appropriate to post as an issue. 
But I want to reference tinygrad in my research since it's the codebase I'm using for some physics-informed machine learning work. 
1) Is there a whitepaper/arXiv paper that describes the ethos/design of tinygrad? Or would there be interest in writing one?
2) Does tinycorp have a preferred way to reference using the code in papers?

**Comment by michbogos** [comment]
A far as I'm aware, there's no official paper on the design of tinygrad. There is some documentation in the docs directory, that describes the abstractions used in tinygrad. You can discuss tinygrad in its discord. There are also george's streams. A paper about tinygrad would be interesting too see, as it can provide a high level overview of the abstractions and its philosophy of simplicity. The paper can also be an entry point for potential contributors.

As far as I know there is no preferred way to reference tinygrad.  I'd say linking to the website and github would be a good start.

**Comment by geohot** [comment]
Yea, a link to https://tinygrad.org is probably ideal. I'll redo the website with the launch of the tinybox to make it better.

**Comment by SamRaymond** [comment]
Awesome will do! Thanks @geohot and @michbogos
