### ISSUE TITLE
IMAGE=1 option gives lower test accuracy with beautiful_mnist.py

### ISSUE THREAD

**Issue by michbogos** [tinygrad/tinygrad#3443]
Recreate:
IMAGE=1 python3 beautiful_mnist.py
This gives 84.5% accuracy.

python3 beautiful_mnist.py
This gives 97.4%

On 7900xt with rocm 6.0.2

**Comment by CalebBunch** [comment]
IMAGE>=1 replaces Tensor.dot() and Tensor.conv2d() with image.image_dot() and image.image_conv2d() which maybe just do not work as well with the MNIST dataset.

**Comment by geohot** [comment]
84.5% seems broken though...

**Comment by CalebBunch** [comment]
> 84.5% seems broken though...

Yes, you are right, it is significantly lower. I can try to look at it tomorrow. I will undoubtedly learn more about the codebase while debugging it anyway!

**Comment by chenyuxyz** [comment]
see workaround in #3857, it's the same issue. closing this one and keep track the root fix in that one
