### ISSUE TITLE
Any plan for C/C++ API

### ISSUE THREAD

**Issue by tada123** [tinygrad/tinygrad#3507]
Hello,
It'd be great to have TinyGrad official API for C/C++ (with docs & examples), like PyTorch's C++ frontend

**Comment by michbogos** [comment]
Hello there, currently the main focus of tinygrad is get amd on mlperf, increase performance and make improvements to the existing api.
Furthermore, I think adding a c++ API would require a lot of work, as tinygrad is written in python.

**Comment by tada123** [comment]
i see 😢. But in future, it might be really useful feature especially where high performance (even when training) is needed. Also, it could be then easily ported to other languages as well (e.g. Java, JavaScript, the C++, ...).

**Comment by terafo** [comment]
Why would it be useful? For whom? Does it solve **ANY** problem? Nobody does training in **ANY** languages you mentioned, and for inference you can just compile model into C and that's it.

**Comment by skoshx** [comment]
Yeah, one of the biggest tinygrad's value-props for developer experience is that it's all just Python, not C++ with some bindings that you then have to build when trying to fix bugs. I don't know why you would ever want to consume Tinygrad in C++ when you can just use Python?
