### ISSUE TITLE
Tensor.rand goes to -inf with default half

### ISSUE THREAD

**Issue by chenyuxyz** [tinygrad/tinygrad#3611]
```
dtypes.default_float = dtypes.half
print(Tensor.randn((128, 128)).min().numpy())
```
often produces -inf

**Comment by skoshx** [comment]
```python
dtypes.default_float = dtypes.half
print(Tensor.randn((N, N)).min().numpy())
```

Raising the value for `N` increases the likelihood of `-inf`. For `N=32` gives an -inf about 1/7 times. `N=128` gives almost every time. 

`kaiming_normal`, `normal` also results to `-inf`. 

The value of `alu4` in the kernel becomes `inf` towards the end for some reason, interesting

**Comment by skoshx** [comment]
Some further investigation. This is the line in the kernel that causes the kernel to converge to infinity:

```c
half alu1 = max((-(sin(((half)(1.5f)-(0.333984*(half)(6.2f))))*sqrt((log2(((half)(1.0f)-1.000000))*(half)(0.6f)*((half)(-2.0f)))))),2.929688);
//                                                                                      ^ val4
```

As you can see, the troublemaker: 
```c
log2(1f - val4)
```

Which evaluates to undefined or infinity if `val4 == 1`. Will investigate further.

**Comment by skoshx** [comment]
Okay, found the root cause. The source of randomness in `Tensor.rand` isn't actually in the range `]0, 1[`, when cast to `dtype.half` because of precision loss. Instead it contains`]0, 1]`, which it shouldn't. This causes the Box-Muller transform in `Tensor.randn` to have infinite values.

```python
def custom_random(out:Buffer):
  Tensor._seed += 1
  if DEBUG >= 2: print(f"*** {out.device}   rand  seed {Tensor._seed} size {out.size:<15d} dtype {out.dtype}")
  rng = np.random.default_rng(Tensor._seed)
  rng_np_buffer = rng.random(size=out.size, dtype=np.float32).astype(dtype=out.dtype.np, copy=False)
  # ^^ this contains ones
  out.copyin(rng_np_buffer.data)
```

Will submit a Pull Request.
