### ISSUE TITLE
__launch_bounds__ is bad on HIP, figure it out

### ISSUE THREAD

**Issue by chaosagent** [tinygrad/tinygrad#3616]
Don't want to forget where we can get perf. #3604 #3615

**Comment by Zaffer** [comment]
see my comment for issue related to __launch_bounds__ here: https://github.com/tinygrad/tinygrad/issues/3536#issuecomment-1978155206

**Comment by Zaffer** [comment]
the __launch_bounds__ macro usage is incorrect for HIP kernel definitions. It's applied to the kernel function in a way that's specific to CUDA, not HIP. HIP uses __attribute__((amdgpu_flat_work_group_size(x, y))) directly on the kernel function.
