### ISSUE TITLE
TypeError in MulNodes' get_bounds method

### ISSUE THREAD

**Issue by JoeruCodes** [tinygrad/tinygrad#3695]
The get_bounds method in symbolic.py, specifically within the MulNode class, is not returning the expected Tuple[int, sint] type in cases where self.a.max is a node (as self.a.max is a sint type alias which could be a Variable, int, MulNode, SumNode). 

![image](https://github.com/tinygrad/tinygrad/assets/79764496/f0b0345f-6215-4685-a7ad-26379d3eb07b)

![image](https://github.com/tinygrad/tinygrad/assets/79764496/2e7ecc7e-21e8-4369-a3d0-be8d3d38db3c)

Because when multiplying a node by an integer, it results in a node instead of the expected integer type. This issue may lead to a potential TypeError. I looked into the implementation of the mul operator for nodes, but they all returned a node by invoking the create_node function...

![nd](https://github.com/tinygrad/tinygrad/assets/79764496/884127f0-53a6-4cec-86a1-c1a008a14de9)

![cn](https://github.com/tinygrad/tinygrad/assets/79764496/14995625-5074-4437-8137-074633037361)

**Comment by chenyuxyz** [comment]
see #3439 for some known type issues. Some of these Node types can be limited to sint but conditional types in mypy is cumbersome

**Comment by chenyuxyz** [comment]
MulNodes is deprecated
