### ISSUE TITLE
improper indexing on conditionals in View.py

### ISSUE THREAD

**Issue by JoeruCodes** [tinygrad/tinygrad#3731]
The problem arises in the **reshape_masks** function in **View.py**

The masks variable is derived from **r_masks** which in turn is formed by reversing **view.mask** which is of type _Tuple[Tuple[sint, sint], ...]_ so when we subtract **mask[0]** from **mask[1]** there might be an edge case where we might be subtracting two tuples which might render this conditional to be obsolete...

![image](https://github.com/tinygrad/tinygrad/assets/79764496/6b4b0fa7-543f-4466-b3cc-c412245b8243)

**Comment by chenyuxyz** [comment]
Are you sure? Isn't mask taken from `next(r_masks, (0, 1))`

**Comment by JoeruCodes** [comment]
oh i get! Thank you for clarifying!
