### ISSUE TITLE
beautiful_mnist does not train

### ISSUE THREAD

**Issue by chenyuxyz** [tinygrad/tinygrad#3794]
Adam is broken after #3763.  Changed Adam optimizer in beautiful_mnist to LAMB can make it train.

need to understand scheduler with assign better
and more robust tests for the optimizers

**Comment by uuuvn** [comment]
I actually found this myself when doing ScheduleBarriers and fixed by doing this https://github.com/uuuvn/tinygrad/blob/77b6568a8f37cd7f774ac00d79f4eb9031c61dfc/tinygrad/realize.py#L177
