### ISSUE TITLE
Wrong PR that should introduce Tensor.no_grad() instead of Tensor.inference_mode()

### ISSUE THREAD

**Issue by Maroc-OS** [tinygrad/tinygrad#3832]
https://github.com/tinygrad/tinygrad/commit/8ae85b2cf5b5e38eaa9675ed3f327474137b4574 this PR is wrong.

This is not **inference_mode()** this is **no_grad()** in PyTorch, cause there is no handling for view tracking and other things that need to be managed.
when a tensor is created in **inference_mode()** should not allow you to set a gradient for it **x.requires_grad()** after that and should throw :`RuntimeError: Setting requires_grad=True on inference tensor outside InferenceMode is not allowed.`

Also, it should be applied to all existing files that uses the old **Tensor.no_grad = True,False**

References here:
https://stackoverflow.com/questions/74191070/why-there-are-two-different-flags-to-disable-gradient-computation-in-pytorch/74197846#74197846
https://discuss.pytorch.org/t/pytorch-torch-no-grad-vs-torch-inference-mode/134099/2?u=timgianitsos

**Comment by chenyuxyz** [comment]
inference_mode has been removed
