### ISSUE TITLE
Vulkan backend

### ISSUE THREAD

**Issue by eugeneteoh** [tinygrad/tinygrad#3853]
Given that a (good) PR is raised, will a Vulkan backend be merged?

**Comment by sojohnnysaid** [comment]
live long and prosper

**Comment by sojohnnysaid** [comment]
> live long and prosper

related: [link](data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxASEhUSEhIVFRUVFRUVFRUVFRUVFRUVFhUWFxUWFRYYHSggGBolHRUVITEhJSkrLi4uFx8zODMtNygtLysBCgoKDg0OGhAQFy0dHR8tKy0tLS0tLS0rLSstLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLf/AABEIAKgBLAMBEQACEQEDEQH/xAAbAAABBQEBAAAAAAAAAAAAAAABAAIDBAUGB//EAEcQAAIBAgQDBQQGBQkIAwAAAAECAAMRBAUSITFBUQYTYXGBIjKRoRRScrHB0RUjQkPwByQzNGJ0kqLhU3OCg5Oys8IWNUT/xAAZAQADAQEBAAAAAAAAAAAAAAAAAQIDBAX/xAA1EQACAgEEAAQFAgQFBQAAAAAAAQIRAwQSITETQVFxBRQiMmGBoTNSkbE0QnLR4RUkQ8Hw/9oADAMBAAIRAxEAPwDx0ToRqKACgAoAKAAgAomAoACAgwAEAFCgFABRAKACjEKAGnleRV647wALSBsarnSl+gJ94+UQG1R7O4JP6XFKzHgFvp9efI/CUoit+hLUpZGl9T1WsBbuwAT1O5PwMOPUVszamW5fVP6jF6L3stcabbHYtwvw+Ji4fmPd6mNmOQYnDgO6Xpk2WqhD0m/412B8DvMtrTJRWtNDQUABABQECACgBq5RkVXE069VGpquHXXUDlwdNmPs6VN/dM582ojilGLX3OkXGDkm15GTOggkqUHUKWVlDC6kqQGA5qTxHlJTTbSfQyMygFAAGAhQAUAFAAGJiLQEtFCtGMUQAjAUAFEAICFEAoDFAAQEKACgAoAKAAMANbA4NKSLiMQPZO9Gmf3xB4kcqY5nnwHUKToCpmWeVazXJIUXKquyqPADymUm2Ld6GY1Qnn/BkhY1UJhYUwMIWJplnCY6rT91jpubod0YG1wy8CDYfCUpMESPY+0ospOwve3UX9ZqmmUCMAWgArQAVoAAiAjsuwn9UzP+7f8ApWnl6/8AjYP9X+x0Yftl7HFz1DA7bM8GHp5XTxGJfuqtMgeyg7nZAvAe0LlRc8AJ5WLJtnnlCCtP+ps1agm+H+xjVuzdQZh9BGreqFB2uaZ9o1OnuXb0tvOmOri9P4/4/f0/qQ8b37CxS7LLVxNelRrgUMP/AEuIqAALa4NgOO4YD7JN5D1jhijKcfql0kNY7k0nwvMuVOzGX/RKuKp4uq60/Zv3WgPUNtKrq34keQmS1mfxo4pY0m/z0hvHDa5KXX4OMnpmIoDFAQDExFsS0WKMARACMBQAUQCgAIgFeIARiFAYoCFABQAUALGCVNV6nuKCzAcWA4KPtGwvyvBgyrmeZVa7mpUNydgBsqqOCqOSjkJi3ZFlZAeUVjSYrRDpmlhcRSUDUurjffcdLRqi0yycJRYHS3EE2PLcR7B2F6FCmoDgsTzHAQSS7C/Qp4jEIxAVNFvG4bxlJqyWyKaiFaACiAVowBEB3P8AJxhWq0MwprbVUoqi3NhqZaoFz6ieT8TmoZMUn0nf9jowK4yRk5r2HxeHpNWqtRCILm1Qkk8AANO5JsJvi+I4ss1CKdv8GcsUoq3/AHLHbQfzLLP9w/zFKZaP+Pm9x5Psh7GwnaWl9B+m/wD7VpnBBudz7QqcOOn2r9bjnOd6SfzHg/8Ajb3f8GniLZu/zdGL2LqU6uHxeBaotN8QEakzGys6G+gnlew8wTOnWqUMmPMlajd/r5meKmpQ9S32iyfHjCUqLYdKOHwwZnfv6TCo5/eEA6rkkgAAn25GnzYHmc1JylL8Pheg5xmopNcL8nDz1jEVoUIUAGmJoRblIsUYCgAIACACiAUABJboaVne47LKP6PYmmoamgZWAAa+17kcb+M5IZJOfZ0Sgkjgp1nMdVgeya1cKawdhVClwDbQQN9NrXBtzv6TneZ7qrg28Lg5SdJiGAgQAEYDK7WW3X8JnNikVZmQXMIJnI3x8I63A0VIB0L52G/ymTs6VRv4HKsPUF3pUzw4qJNsbSLJ7NYK+1BfQsPuMe+XqRSJF7LYNf3IPgzOw+BYxOch0jke1uQUKWh6SlbtZluSLEcr8LTXFJt8meSKOYIncjEFowFaAhGIBjRAAMepioAMSeJMdIAMT1MVACACMBMNza14qAKygDaMA6YxjWEliLAjRSFGAIAAmIBQAEAFEwOvyHs1SrYZqrFhUF2U32AXgCOh+M48uZ20dEMaVM1+1YKYAgczTB8tQP4TLBzkKyPg4HAYY1KioOZ+U7cktsWzCKtnq+Dod3SVLXBsvnfkfSedZ09nnvbPLqdDElaY0qyK4UcFJJBA8PZv6zvwybjyc+RUzCmxmCAhQAbilGkG++q3ymTdikirTW5kMUVbLh2maN+i7TxBVbrWIb6tib+G3OUF/k0cm7VVaZtU9ofAyJR9C4S9Tu6ePthxVIPWwFzvvaZUaGJ/8qrVW001UfaYX+F7zRRVckMrZ67tTBqkX1rsvAbNKiknwKXRxzCdq6MGC0YCMBDCYgNbshltPE4unQq6tD676TpYaULCxsek5NbmlhwynHtF4oKUkmUM2w6069amt9KVaiLc3NkcqLnmdpthk5Y4yfmiWqbRVtNBAtABWgAtMBB0x0AQIAPAjGHTHQDWWTJCJRBFCMYDYACACiAUQCtE2NHqmWYc0sLYfUA+Nh+M8qTtnWij28cjBhetVB6AMfwmumX1mc+jF7C5dqZqpHAWE01E7e0IRpWzvVTUQvDSNR8+A/H4TlRfR5r27qXxjj6iov8AlDf+09DAvoMMj5Oem5kKABgMdUXULeN5yt0y2rK+Hp+15Qk+CILk2stwIc728By9ZmzdI6bLcoFOx224NzHreG5lUcpmz0nrE01AS4AsLXtxPrHYHpmAphsOm21uEzKMPF9lqLsCVPmDvfjc9dyZanRMopkWKyV0ommWL/rE0k8bEgWPXjCMvqJa4Ob7Q4daeIqKoAA07DgCUUn5kzsxNuKsyl2Zs0JA0AIjEI6P+Tn/AOxof8z/AMTzg+J/4Wf6f3NsH3oyu0H9axH94rf+Vp06f+FH2RlP7n7s3sowuGw2CGOr0RiHq1DTo0nP6tQt9TOOfunry85x5p5c2fwIS2pK2/M0ioxhuau+i1lv0XMxUo/RaWHxC02qUqlAaEYra6unqOvPhbfPKsujcZ73KLdNP/0VHbktVT/AzKDh6OWLiXwlGu/0k0/1g/ZKE7kcbePXwErN4mTV+FGbitt8CiorHu23yQZ5hsNXwK46jQWg61e5q00JKNcXDAHgfd+J4y9PLLj1DwTluTVpvsU1Fw3pUWcdTwmXLSpvhUxOIqUlq1GqsdCBr2VFtbkd/D4Z43m1blKOTZFOlXbKko46VW/yRdqVovgsJXp4alQaq9XUKagbJcAXtfxl6PfHUZMcpuSSXf5FkS2KSVWcsqz1aMQ6Y6Aa6yZdgESUNAMYAgAIgBABRAOordgOpH3yJv6WVHs9crjThx/yx/nWeSzqjyzL7bo1TChQCzd7T0gbm5uAPnNtPKp8kzVo08iy9aFJU5gXc+POZSk27GXMtbWC/wBYkj7P7Py39Y0wlweTdosSKuKrOOBqEDyX2R8lnp41UUc8+zOmhAoCFABXnNNUzRBIs3mPukeQJUzRyzFaGHSQzZG9nOchaPdqfacWPgp4/GJIbOT7wAg9JokTdHomV9ocP3ClnCkAXB63taQ0XRuUiCL9JmxGf2kxYpUWcW1AqR56haaYlcqJl0eZV67OxZjdmJJJ5kz0EqRg3Y0RiAwgBEYCNrsZj6WHxlOtVbSia7nSzHdGUWCgniZya7FLLglCC5ZpikoyTZtY6jkdR6lU4rE6nd6hApm12JYgXp9TznJjlroxUdkeOO/+S34L5tlTKs2wtTDHB4sPTpioatCpT9tqRJN0YWuw3O9t7nhtNc2DLHL42Gm6pp8WTGUXHbL9CxhswwGBSo2EqVMRiKiGmtR6ZppSVuJAI3PDrwHDeRLDqNTKKyxUYp3SdtjUowT28so/pCj+ixhdX60YnvdOlraNJX3rWvz4zfwJ/OeLX07aFuXh7fOxU8fR/Rj4Yt+tbECoF0tbSAAfata+xPGU8M/nFlr6VGg3Lw9v5NCvmWAxiUzi3q0a9KmKZemmtaqrwJFiQePTiZhHBqNPKXgpSjJ3TdUU5Qmlu4YM+Ufo3A2BA7zEEA7nTqNrkcTwj0t/OZb9IhP+HH9TmQs9UxHaYAR1BJkIikIYoDBGIUQAiGCAFvK6Wqqg/tD5GY5nUWXBXI9ZqUe9RVvYBlY+IU3t8QJ5jOhcGgpKi42iEZub4d6iaaZALkBiSdlPvW9PvjRcSfvO4oOzfu0J8NllQVuiJcni5JO54nj5z1kjmfY2MkUYCiAIW8xyrzLiOYzEoehklJk4wzsAdrNfcnpa/wB8LKNHD5CpsWe/DZRy8zCwOsy3K8OE0NSUgHV7QuSeVyd5Fjs1WbS23Ar8x/oflIKXJyvbav7Cr9Z7nyUH8SJ0aZXKzPI+DjDO45yRYAJhACPTAA6YCHaY6GELGAdMKAcEjoB2mA6NfKs0o0U0tgqNZrk66pJPgALbCcufTZMkrjlcV6IuMklyrG51nFTElAypTSkpWnSpjSiA2v5k2Hwj02kjgt223232xSk5fhIoKs6yA2jGR1RvIkJlWZoBQAUABAYIAKIZv9kMKWq36Tj1MvI1xrzPTqSFVE4WzQmqX08OcAsro2/GMZk9va5TBOPrlF+LAn5AzowK8iIk+Dyoz0TnJMNhqlRgtNGdjyUEmJtLsdDsXg6lJtFRGRuNmFtuo6iCkn0JogtKEECD5AGmxJ6znyxp8FRJBMDRGlpYUS45BVHkSb/P8IvMtj8vxbkBRVRfMb/E2lJI1xpPs6rBVsTpH6yjU67adXqLw2R9TRwjRoLVLcVKkcrg8iNiOW8xkqMKpnF9rcRqrBeSL823Py0zt00ajZjkZhhZ0GRKixpDCVjAbpioQQsYElDDs7BUUsxNgqgliegA3MJSUVcnSGlZZxOVYikNVWhVpi9rvTdRfpciZ48+KbqE0/ZjcGu0Ow2U4ioA1OhVdTcBkpuwJHEAgQnnxQdSmk/yxqDfSI8RhKlM6aiMjfVdSp+BmkJwmri01+BNNdkmEy+tVv3VKpUtx0Iz289Ik5M2PH98kvdjUW+kb3aLAClg8FekKdRu97y6aHJUrp17X4Hn1nBo8zyanLUriqrnj9DTJGoR45OcAnqGI8LGAQsAIao3ksTKQmSAUBigAoACIAQGdh2GWxJ8Z52odyN4dHoS8pzNFElawG/KAikp3uRYfxxgM53+Uhr4en070f8AY9p1aX737EzVI8+w2HLmwvYbsbX0jqZ2zkoq2ZQi5Ojv8gw9KnSvYKu5JPE25sec4JTc3ydGxI5TtPnf0qoNIslMEJtub2uT04DaduHHsRzzdmMBNiAgQARExzdFRApnOUmb2TlKlNqT8zeS/UtMv5dktMkqbHzk2y+DbwuRLTsV0xOw3FjGVFpqWbYKLn0iUbdCs83xFUuzOeLEk+s9OMaVHM+WMUSwJkWVQDikYDdMBhCwA3OyuB1vUqNWeilGk1So9P8ApNPCybbE77+nOcOvy7IRioqTk6SfX6mmONtu6o3aWNFbC5gEqVqlJadEp37a3DXJY+G4At/ZvOB4Xjz4HKKUm3e3o0u4yroqJialPKqZpuyE4pgSjFSRoba45bCbvFDJ8Qkpq/pXZNtYlXqLM8Q9fK6dWqS9SniDTVzu2koTYnny+AhghHDr3CCqLjdfkJPdjTfqTdrcdWw7UsNh3alRWgjDQdJdmvqYsNzwHxkfD8GPPvy5Vulb78h5ZONJcIh7SVWfBYBnYsxFe7MSSfaXiTxmmihGGrzRiqSoWTmEf1OYAnrmA+0YCiAiq8ZMhMz1mSAUBigAjAAWgCFAZ2HY1rD1nl5ezpj0d3QqflMWA3E4m508h8zAKBuRa0dAU88yoYig1NiRb2lI5MOF+o3lY5uErB0yrl2TUqKaABbiTzbxbqZU8jk7YKl0ct2nzZLHD0eF7MRwA+qJ04MTvcyck/I5e07DnEBABwEAAw29R+MxzdFRGMJgimOo1ypuNo6sm2jZwmfhbHnzk7C96Ohy7tAKpstz1ABktUO0yHtSSaNzxLrt4WJ9Zen5mE+jkgs7zEcqyqGTIsYEmiMY0pEIAWAGhk+Z1MM5enpOpSjo41I6niGEw1OmhnjtlxXKa7RUZOPKNGt2kvSqUkwuHpCqulzSUqTbhwO9vGc0fhzWSM5ZZScerLeW01S5KL5mxwy4bSulahqat9WogjytYzpWmSzvPfLVUQ5fTtEczb6N9F0rp7zvdW+rVa3la0Xyy8fx75qqDd9O0t4btHUWkKNSlRrogsnfJrKdADfh5zHJ8Pi8jyQk4N906spZWlT5KuOzV6tKjRZVtR12YXuxc3YsOHEcrTbDpViyyyJ/dX7EubaS9CgBOogdaAAMYyGtxkSJZniYoEGMYoACACgAomM6XsnVsCD1nm5Ozph0dnQxIG5PgJiMkWou1/WNIRdSsolEsbWzBAOIifIJHJdre0llNKkRqb3iP2V6eZnRgw27fQpSpHDWneYCEAHIpJsBcnkNzADUw+XotKs9U3qJT106XInWoOsgg2CljYdIp2kTvXkc8cUdRJA35DYDymElYoypky1AZlTRupJjlQk2HEwHRvZb2buA9U8/cHTxP5SXItYzqsNh1UWRQoHQSWylExO1mMQBKQILFwSL7gWIuenGbadVKzPK0lRgmn8p3IyHKsoKJlWMZq5TkOIxIY0VDaSA12VbX3HEzl1GtxadpZHV/guOOUui83YnH/7If9RPznP/ANW0v837MrwZ+hgYjDPTYo6lWU2ZTsQZ6EJxnFSi7TM2q4ZGBLEOtAQrRjFEKgRgIxCEIDCYANMAIKx39JDJZREzQIMBigIUBggBNRoalc7+ytwB4sq7+A1fdJn9rBPmjYyvBuhG/iQbjl1nnSZ1Lg6EamS23HfeZDM/MM4qUrbEi5B236iVGNibojqdrPZ9lTfx2E3jp5Pszc0YONzKrVPtMbdBsB+c6oYYx8jNzbK9Gize6rN9lS33TUlll8uqoL1EqKOnduT91h6kQfBLkikmOoqd6TN4NU038wq3Hxkbyd7NXB9q0p7Jg6I8dVS582JuZSyfgiVvthq59Tc3OGRb3DaXckqwsw3PQmOX1KhLhnN16BUkcbc/xmLTKIpID0qsOBhSKUmjWo9pcQqBAV25kXP3xeGjX5iRBXz3FPsarW6L7P8A22jUUvIh5ZvzIMJhqlV9Kgsx/i5PTxmkU30Zt+p3rZUtRKasf1ugA1F5st1Ooc+HHjOmEfp9iVkcfYysZldWl7y7fWG6/Hl6x0bxmpdEAWBodR2e/qGP+wv3NPH16/7vB7m0PskVMH2WxzaKlJbarMlQVFFgdw1wbzbL8Q0cbhPtdqiY4p9o1+0eATGY8UUqAMtAB306hqUk6SARvYj42nFoc8tLpHklG05cL3NJx3zq/I57FZMt6YoYiniDVYooQFWBAB3BPCxG89LFrG1J5YOCir59DJw9HZdbs5QVu7qY6itXgU0sVVvql72B85gviOSS3xwScfX8ew/DXW7kq0uzmIOJ+ikBXtqJJ9nR9cHmJvL4hiWDx1yv3v0J8OW7aS/oTCXt+kqN72P6t9jw3N5l89nq/l5f1RWyP8xVyXJ1xBq/rhTSkhqF2QkFATdiL3XYXtvN9VrHgjF7LcnVX5kxgpXz0WT2aDqxw2KpYhlGo01utTSOaqSbzFfEtsks2NwT83yh+Ff2uynlGTvXVqhdKVJLB6tQ2UE2sB1O4+Im+o1kcLUacpPpImMHLnpFrNchp0cOMQuKSqrNoQLTI1m51WJbgAGN/CY6fXyy5vCeJxa5fPQ5Y0o7rskTszT0UXbGUqZr0w9NKiFb3ANi2q3MC8h/Epb5xjibUXTaY/CVK5VZytY79Z6LMWU1maEgwGCMQohhAgFiw2O7uoCN1sVYfWU+9+foJL9DG3dna4SolT20NwbefqJwZMTizshkUkaaAAC8wNDmu1WL4KtrEm5HVbXH+YTs02P/ADMynLyMPB4SpVcJTUsx5dB1J5CdtWYtpK2dTTyinhLGrQ7482LMFB6KB953mihRhLI30aeBfBVjbXWpn6j1GK+h/OWZtsrZnlFeldqVRgORDG3yMdAmZ+Kdnt3oFS31wGt5XElxT7Q7KNTB4bnRAvzVmUj0vb5SdkfQdsjpZNhzwq1B4EKfnt90FBA2Ox2UbArU90BCStrjfSxt4AqfITPZUqKu1ZQbJGP1T4qbH4EWjeKxbivUyKsNwA3qAfy+ch4ZD3IqHL617d09/sk/OTsl6DtGngeztRjd/YHxb8hNIYW+yXM6rL8HTorpRbX4nmfMzojFLozbstU3Fl4kWJte3FmPH1k4+b9ypeRYp1lHDb7QP4G3ymhBDVwGHq3sAjf2Db/KdvhFVmscskXcuy9qWCxwvq1ILWBvwblPE16rWYPc7sGRSxyZyC4moBYVHA6B2A+AM9R4oN24pv2Jtm32BH87H+7qfdPP+L/4b9UaYfuKnYzF06WKpPUIC7rqPBdSkAnwv981+JYpZdNKMe+H/QWJpSTY/E9lcaKjIKLPdjZxbSwJ94twF733k4viWm8NSc0qXXmvwDxTuqNTOqlc4mkmELVK2GoKlR6djdhswN9jxFweZ8Jx6WOJYJy1H0wnJtJlzb3Lb2kXsIuLxDrTx2AVlbY1gmh0297UCeduFpz5HgwRc9Nnpr/Ldplx3SdTiZWW4TuTmlK9wmFrqCeJAVrX8bTr1Obxo6bJXckZxW3evwxdlcnr0K64qsO6o0lZ2qMVsylGUBbHe+oH/W0fxDV4suJ4cb3TlSpe4YoOL3PhIWHpHGYFqVD+kTFPXNK4DNTfVYi5sSNY/wAPlJnL5XVLJl6cFG/JNAlvhS9Sr2sp4hgjHDPQoUUWnTVyuxNrnY7sbDhyW/WbfD5Yk5VkU5yduicu70pIj7Vn+b5d/dB91OHw/wDjaj/V/uPL1H2OWqneejI52VQZCAMYCgMUADiEKpqtx4HoOHzP3TNy5oiXRSoU9RhFWZPg3Mv7ymbobdRyM32JqmTuado6KjmrMLMN/CYvR47s1+Zkc/WXvqgSmLIt7XJNrm7MTzJP4TTalxEpNpWzq8qppQSyDj7zftMfH8ptGNHPOTZYq5ibWvtLIMzFUAfaGxETRRJTxLFQp4DlyvBCGuLxiK9WhE0Oyo+HI3Ekonw2IuQrc7r8dx8wB6yJuqfoVFeRIKQlkWSBIATLGmIcJViJAIWMLLy6AD5SMf2jk+RumWSMdYgLGHxjW0liPAEgH0kyhCTTcU2itzXCZFjKFKpxFm+sPxHOU0mVDI4mGxqUmNmZTwurFSR5jlMpwjLiSv3OuMrVogJj6GTLjqwXQtaqFtbQKtQJbppBtM3gxSe5wV+tKw3P1IaNZ09x2T7DMvl7plTxxl9yT9xJtdEhzCv/ALer/wBWp+cj5fF/Iv6Ie9+pqdnsagp40VKgDVcNURdbbu7KwAu3Ezj1uKTlh2R4jJN0ukXjkqlb7Rh1KzMArMxVfdUsSq8vZBNh6TvUIp2kr9TO2NVyCCCQRwIJBHkRwjaTVPlAGviqjiz1HcA3Ad2YA9QGOxkxxwg7jFL2QNt9kVbEO1gzswGwDMWCjooJ24Dh0hGMYt0qsVsq1W3il2SyESUAbxjFAB9GmWYKOJ/gxN0gK1aopYjcKCRv71uRI6znl3ZN3wWcNhSu97jbfoTuAek2xSTdETg0a1JJ1IxY/EllWwG7HSvmf9ISdIrGrZby6mtIaR7x3Y9T+UmKoc5WXC5MszDRcHY8ZSES1BYRjK1rSQHq8BD4wIXWJjKWMoErdfeBDL5qbj7pElaoqLouBwQGHBgGHrvb03HpFB2hyVMlQzSiCQCFAG0YE1MXNv4tz+V5E3UWOK5AxvvLSpCYIwGtJERsvTiOHnABwe4vADPzNdg3Tb4xSN8L8jNJknQNJiAaTAQwtAAaoALXAAFogIy0AGM0QiCoZEuxAESAMYwQABr6OHG23hf+DM5viib5GLSLHUG3O5ueJPO/SZRp8MGmuUbWXi3stwJ3FvvHUbbx5MMkt2McMkXxI3HKaAtM07ggkFWGoW3BbTcERwWoXLB+F0itjhUGgBQoAuCwJBZgLkX2PQevWdMN0lcjGdJ1EcMRjgLrUp1B9RkUegNppUvIz4Bgc3p1GKOvd1BxU9fCOM0+BNUWsRhiPaWW0IctbUvjcQTABgAwiFDEGhYDrwEROskYygdynT2l+yx3Ho1/8UhcS9y3yiZZoiCYGAh4jAlpnc+APxPs/cW+EifLS/8AuC102NM0IFEAGEAGkQAjUbkdd/z/AI8YhkWNS6EeF/hvBlY3UkYJaZnYNLQEMLRAMZoAMLwENLxADvIWAC8VgMLRWBE7SWSOWCGGMYGNhfpE3QmymSWPnMe2ZG3hXayhlRrDTcDSxWxFiw2OxtuJfy9+ZSy0beXYekQNR5EXbkb3FwOdjb0mO7NF7Yo1rG1bJ6mECoXQAsNQALALcbKw3vpPjNceXPJ1RnKGNc2ZGBfEUtnxKMvNG11R6bbehnRCMo9sxbTNYZjhNgKmlvEaVPkCSRNdyIaZFm2VCuodCBUA2YftDoT+McoKXPmCdFfIs1Y3pVPeG2/HbiJMJeTBo0ahGqw6X/D85YhaowFeIBpiGAGABvACHEC2mp9U7/YOzfDY+kia4teRUX5Fm0tO0SOEYD1MBEwFhf6x+S7C3qX+Ehczb9C39pHVqBQSb+AHEk7ADxJluSStiSt0Gm9xwI5EHiCNiCOsUZKStCcWnQ6UIaRABh4gxARVDfb0iGuDm32JHQ2+EzO1MjLxAMLRWIYzRWAwtCwGlorEMJiAF4ADVFYDWMTESCNDDGMrYl+XSZTfkZsdgkuY8S5IkbuHWdaRmy/RWNEl9KOpb8r7ygJEpgcAIwDUw6OLMoYdCAYNJ9hdGU+HfCnvKZJo/tpxKD6y+EycXB2uiuJEGbUgMRRqJ+8424G1t/gR8IT7TQl0X8TUs6t1JX5Aj7pYIe/WMBB4hDgY7AUQxWgANuEABh2NtJ4qdPmP2T8LfAyIcOipepMGmhItYG8VgWqlUHSALWRQftcXP+ItIx9X6lT7os5Mp+kU37oVVpsCylda6qgZaV0LKGuQ9gWAuLk7TPUyqNGmGPmHPAVxVQFFQtZmFM6qaub2AYMwBIF9FzbSZOml5DzR4sqzqOcBjAhrttEBApgBg5iLVG87/HeYy7OuDuKKZaSUNLQbAYzSQGEwEAmADbxCGkwAbeIYCZLYiwJaGJjbeDdIGUSZzmZo5ak6sS4M5M2aIm5mXFO3yjQGhRqeyBKAlWADxGIeAOfrADi80rtRqCiQD3ZbumvuEexF/ITklLa9prV8l7Nqx7pWHJlPyI/GbSfFkonweI1LGmIkZoAPWpACQGMQ68BigA0mzA8j7J9fdPx2/wCKRLjkqPPBJqmhBHWNwB1IHpz+QMzm+Codk6tKXoI3uzWb4WhQxfe0kxFSs9OmuHa9ilJSe8c2OhdVR9+O205csXPJS8joj9MbbMvGZpW7srVKlS61AQm9MpqC01Ym4plXf1N/2jKeLw2pIPEU7QrzqOYazCxJ4CAGcmLWoSVNwLgHkfH75Kd9DaocpgIxc7FnB6qPkTM59nTifBmlpFmg0mIQ0mAht4gATEMbeAAiEKIBpMQiyJoiiHEttaRNkyK4mRJrYEWE7ILgyZqUWmhBcHL4ywLlOoeDC0YFimYwJAYAVcxzBaS/2iPZHU/lJlJJFQg5M4XHk6tRJJO5J5mcOTuzdqjQx2JvSA8AfgRNpS+kxiuSfLK3siVB8CaNK80ER67RDLCVIxMlDR2A68BEdexVrmwsd+njE6rkauzLxuZYhl7xKWlABqYDULjYnwBIJ9Zzb5VwbOKsOW5qGe1Xb2ToYWtrOw1A8BbULjheT4jbVjpI10edaMB+Fpql7bkm7E8SfGOKSG3ZPWUOpU7gi0bVqhJ0xqHSoHGwA+AiSpUJ9mH2kxraVpqbaydXkLbfP5TLLJ9epcfUmyxAtMCVFUiWWg0oDKz8e4fMfcZnkNsTMe8yNRpMBAJgA28QwQEKIARAKIQDALP/2Q==)

**Comment by chenyuxyz** [comment]
close as no planned

**Comment by stalkerg** [comment]
Is it possible to register back-end outside of repo? Or we should support the fork for a such backend? 
It's https://github.com/tinygrad/tinygrad/pull/3898#issuecomment-2053930009 a valid point but what about community which want to run Tinygrad on the different devices?
Easy to add support a new hardware was a main pros for this project.

**Comment by chenyuxyz** [comment]
fork is encouraged. easy to add support != every device in tinygrad repo

**Comment by stalkerg** [comment]
sure, but will be good if it possible to use new render outside Tinygrad without full fork or monkey patch.

**Comment by brunteless** [comment]
Hi, is there any chance this was reconsidered and could be part of the roadmap (or at least be supported)? There were a couple of PRs opened for this. 

Merging this in would open a lot of cool stuff on Android, since Google is slowly deprecating OpenCL (OEM inconsistencies) in favor of Vulkan.
