### ISSUE TITLE
Tensor.expand inconsistencies 

### ISSUE THREAD

**Issue by geohotstan** [tinygrad/tinygrad#4070]
reproduce:

```
In [5]: torch.ones(1,1,1).expand(2,3,2,3).shape
Out[5]: torch.Size([2, 3, 2, 3])

In [6]: Tensor.ones(1,1,1).expand(2,3,2,3).shape
Out[6]: (2, 3, 2)
```

Before this `expand` in tinygrad would have hit an `exception` if I'm not mistaken...
Not sure if this current behavior is intended

**Comment by chenyuxyz** [comment]
torch behaves based on broadcast rule (prepend 1 on tensor before expand) https://pytorch.org/docs/stable/generated/torch.Tensor.expand.html

we can refactor _broadcasted and use that to match
