### ISSUE TITLE
CommandQueue Plan

### ISSUE THREAD

**Issue by geohot** [tinygrad/tinygrad#4078]
- [ ] Write memory planning
- [ ] Switch JIT to new style JIT
- [ ] Support graph?
- [ ] Lazy cache -> CommandQueue

**Comment by geohot** [comment]
CPU should be in its own thread, the binary should be raw x86/ARM, and LLVM/CLANG should be compilers, not runtimes.

tinygrad can support OpenCL/CUDA/HIP/METAL as high level drivers, and KFD/NV as low level drivers.

Low level drivers support "graph" and speed, high level drivers don't. We will lose support for METAL graph.

**Comment by chenyuxyz** [comment]
CommandQueue was removed
