### ISSUE TITLE
RFC: Docs / Website for tinygrad

### ISSUE THREAD

**Issue by skoshx** [tinygrad/tinygrad#4083]
Wanna start by saying that I understand how important writing good & correct documentation is. As such, this work is more towards writing the infrastructure to support bounty claimers to easily write & deploy docs, while providing an amazing docs experience for the end-user.

### Motivation

I was seeing some chatter in the Discord about using the same boring libs for the tinygrad docs / website, and I just thought that tinygrad is such an awesome and cool project that it deserves a proper site that reflects that.

I’m opening this issue to gather some feedback, whether I should continue with this docs site, or not.

### Quick Preview

![Screenshot 2024-04-05 at 14 31 34](https://github.com/tinygrad/tinygrad/assets/16806818/3fbd91e7-84c5-4218-9eda-b9bf967bf3d4)
![Screenshot 2024-04-05 at 14 31 11](https://github.com/tinygrad/tinygrad/assets/16806818/8a61e13f-4d01-40b8-ba42-fe158a5083e6)
![Screenshot 2024-04-05 at 14 31 03](https://github.com/tinygrad/tinygrad/assets/16806818/359b1c0f-c167-4727-a552-1a50c7c0673e)

### Features

- Docs are written in Markdown / MDX in the main tinygrad repo, same as now, in the /docs folder. We can use MDX if we want interactivity or custom components like callouts etc.

- Docs site is super optimised, 100% statically rendered, get’s re-rendered every time docs on Tinygrad GitHub changes.

- Algolia search to search docs (alternatively could also implement super basic search for free)

- Dark & Light mode, defaults to system theme

- Thinking of implementing: Ability to run code examples to show how tinygrad works right in the docs site (possibly using WebContainers https://blog.stackblitz.com/posts/announcing-wasi/)

Should I keep building on this, or do we want a Microsoft-level docs website?

**Comment by Zaffer** [comment]
is this a custom package? what is the complexity of maintenance and updates?

**Comment by geohot** [comment]
I'm okay with very lightweight well maintained static site generators. Which one is this?

**Comment by eichenroth** [comment]
Imo this would help a lot to get more people to contribute! 🚀

**Comment by skoshx** [comment]
So it's built with Next.js, so it's technically not a static site generator, but that's not really what you want either. What you want is that the content on the pages is static, but updates whenever the docs content in the tinygrad repo changes. That way you don't need to deploy every time someone contributes docs to tinygrad.

So with the setup I was going for we have best of all worlds, the site content get's re-rendered when docs changes, and they are static, so they work without JavaScript, perform super well and get perfect Lighthouse perf scores

@Zaffer the UI is custom built, but the complexity of rendering the docs pages is super low, it's just one file, that renders the page content based on the Markdown.

@eichenroth Totally agree! Would also be super cool to try to get some interactive sandbox / demo thing on the website where people could use the `ops_python` to play around with tinygrad, right in the browser. Would be super cool I think

**Comment by Zaffer** [comment]
It does look really nice, well done on the design. My vote would still be to use https://squidfunk.github.io/mkdocs-material/ (unless I am missing something) this would be the same effort, similar styling and is constantly adding new features and updates. I understand the docs package is best practice now and is used by FastAPI and Pydantic.

**Comment by eichenroth** [comment]
> That way you don't need to deploy every time someone contributes docs to tinygrad.

That does not matter, because we have CI/CD.

I am advocating strongly against anything custom build, haven done so multiple times in the past and went through a lot of pain. Also, contributors of tinygrad do not care too much about design. The most value is added with a well structured documentation that allows a quick deep dive that looks shitty.

**Comment by skoshx** [comment]
> Also, contributors of tinygrad do not care too much about design

I think it's more about giving each user the "wow" effect every part of the way. I strongly believe that if you want to change the status quo and get adoption for something new, you have to focus and improve on every tiny detail, like Tesla. If Tesla would have used the same infotainment system, same manufacturing methods as every other car manufacturer because it was a "best practice", do you think they would have won electric cars?

I do hear your concerns, but I do think that while the design & layout being custom, the docs generation logic is not complex, and already supports everything needed.

But I appreciate the feedback!

**Comment by eichenroth** [comment]
There will be a zero percent chance that documentation that is not trivial to maintain will be merged. Dont get me wrong, your draft looks super good, but other people have to work with and understand it.

My guess is still, that a well structured documentation will be much more relevant than a beautiful documentation.

**Comment by skoshx** [comment]
Yeah I totally get that, but just because it's custom doesn't mean it's not trivial to maintain... Like I mentioned earlier, the docs will be written in Markdown and will be already well structured in the tinygrad repo, this docs site would just consume it and produce beautiful looking documentation with more flexibility.

The way I see it, is you will either way have the docs written in Markdown in the tinygrad repo, and the only choice you have to make is whether you want the docs site / tinygrad website to look good.

If the custom website ends up being a pain to maintain, you can always just switch to any of the boring ones with minimal effort, so why not try it first?

**Comment by geohot** [comment]
I definitely don't want any god damn javascript running in the browser. javascript ruined the internet.

**Comment by skoshx** [comment]
Yeah I mean I do agree that was the case with React for a long time... These days however combining static HTML generation + JS + Streaming can actually make pages load faster with link preloading etc so it's definitely gotten a lot better.

But yeah, keeping it a JS free zone is totally fine by me. We would need to throw away any kind of search functionality though.

Anyways, should I keep building on this, if docs input is markdown, and output 100% HTML?

**Comment by geohot** [comment]
Is it using a mainstream static site generator. Which one? We don't want to support something custom unless it's <100 LoC

**Comment by skoshx** [comment]
The one I intially played around with was Next.js (Next.js build was static too, but it ships JS to optimize page transitions through link preloading), I was thinking of writing it in Astro to ship no JS

But yeah, can't do the above in <100 LoC (Tailwind styling, components etc take lines), that amount of lines only affords you basic docs unfortunately :D

I might make a docs fork though just for a bit of fun :P

**Comment by devlouie** [comment]
Chiming in, Hhnestly, as much as I hate that I am saying this, having worked with every single website platform you can think of - in 2024 - go with a vanilla wordpress instance, seperate your marketing website far away from any technical work for the time being. 

Spend all efforts on products instead. 

A word to the wise, and you know this already, you're eventually going to hire a marketing / sales team and they will yell and cry for a simple CMS based website. They will want to integrate their (x) information systems, CRM's, ERP's and what have you, and you should not be wasting bandwidth in those decisions. 

Wordpress 6.5.2 is open source and excellent, the stock theme works fine - extend the theming as much as you want but keep the stock block building functionality. 

Could even run headless WP.

Do not roll any sort of custom stack right now, it's too much headache. 

The UX / UI above looks great, happy to also contribute on that front - websites I've made recently; VesoGDK.com — VesoNexus.com - and I can roll something together in wordpress with the rest of the people here. 

Stick that alongside a custom plugin for docs or other docs software. 

It's just a simpler business decision.

**Comment by skoshx** [comment]
> seperate your marketing website far away from any technical work for the time being.

Can't disagree more on this. Tinygrad is a highly technical product and as such, the "marketing" website should also cater to technical people and be highly technical (technical people just want the technical specs, facts, benchmarks how to play around with it etc)

> you're eventually going to hire a marketing / sales team and they will yell and cry for a simple CMS based website

💀 i dont think the tiny corp is that kind of company

Anyways, this feels like a bit off-topic. A website can be built a 100 different ways, but George has mentioned not wanting to spend too much lines on it, so I think it will be some basic like MkDocs

Should I close this?

**Comment by massivedynamics1** [comment]
@skoshx docs are available at https://tinygrad.github.io/tinygrad/ using https://squidfunk.github.io/mkdocs-material/
George posted on 
https://twitter.com/__tinygrad__/status/1783411229639536891
https://twitter.com/__tinygrad__/status/1783410771885728016

![Screenshot_26-4-2024_184048_tinygrad github io](https://github.com/tinygrad/tinygrad/assets/53446766/23a4f082-960f-41be-983e-d53423710fd7)
![Screenshot 2024-04-26 at 18-41-48 MNIST Tutorial - tinygrad docs](https://github.com/tinygrad/tinygrad/assets/53446766/0186d2e8-201a-48ab-837c-c28fdc8a3c77)
