### ISSUE TITLE
Bug in View._reshape_mask

### ISSUE THREAD

**Issue by PaulGustafson** [tinygrad/tinygrad#4109]
The following code incorrectly evaluates to True:

```View(shape=(2, 3), strides=(0, 0), offset=0, mask=((1, 2), (0, 2)), contiguous=False).reshape((3,2)) == View(shape=(3, 2), strides=(0, 0), offset=0, mask=((1, 3), (0, 2)), contiguous=False)```

This is wrong because the mask on the left has 2 elements, but the mask on the right has 4.

The source of the error is this branch in View._reshape_mask:

```    
else:
      next_mask = next(r_masks, (0, 1))
      # combine if the mask can unfold continuously
      if mask != (0, old_dim) and next_mask[1] - next_mask[0] != 1: return view.mask, True
      mask, old_dim = (next_mask[0] * old_dim + l, (next_mask[1] - 1) * old_dim + r), old_dim * next(r_shape, 1)
```

**Comment by PaulGustafson** [comment]
Another couple examples -- 

```View(shape=(3, 4), strides=(4, 1), offset=0, mask=((2, 3), (0, 3)), contiguous=False).reshape((4,3))```
and
```View(shape=(4, 22), strides=(22, 1), offset=0, mask=((1, 2), (0, 20)), contiguous=False).reshape((22,4))```

**Comment by chenyuxyz** [comment]
it probably needs to explicitly check the end condition for `next_mask`

**Comment by PaulGustafson** [comment]
One fix would be to replace the last return statement with

```  
if prod([m[1] - m[0] for m in r_masks]) != prod([m[1] - m[0] for m in new_mask]): return view.mask, True

return tuple(reversed(new_mask)), False
```

But we/someone should walk through the code to make sure they understand what's going on (I don't -- the nexts + two levels of dims + strides are pretty complicated lol).
