### ISSUE TITLE
Segmentation Fault when running with HSA

### ISSUE THREAD

**Issue by Hprairie** [tinygrad/tinygrad#4217]
Running the following with a fresh conda environment with python 3.11. CPU 3970X Threadripper. GPU 7900 XTX.  Ubuntu 22.04.1 .

```
DEBUG=3 python3 -c "from tinygrad import Tensor;
N = 1024; a, b = Tensor.rand(N, N), Tensor.rand(N, N);
c = (a.reshape(N, 1, N) * b.T.reshape(1, N, N)).sum(axis=2);
print((c.numpy() - (a.numpy() @ b.numpy())).mean())"
```
Results in.
```
opening device METAL from pid:9140
opening device HSA from pid:9140
opening device NPY from pid:9140
scheduled 4 kernels
*** HSA   rand  seed 1713494129 size 1048576         dtype dtypes.float
*** HSA   rand  seed 1713494130 size 1048576         dtype dtypes.float
  0 ━┳ STORE MemBuffer(idx=0, dtype=dtypes.float, st=ShapeTracker(views=(View(shape=(1024, 1024, 1), strides=(1024, 1, 0), offset=0, mask=None, contiguous=True),)))
  1  ┗━┳ SUM ((2,), dtypes.float)
  2    ┗━┳ MUL 
  3      ┣━━ LOAD MemBuffer(idx=1, dtype=dtypes.float, st=ShapeTracker(views=(View(shape=(1024, 1024, 1024), strides=(1024, 0, 1), offset=0, mask=None, contiguous=False),)))
  4      ┗━━ LOAD MemBuffer(idx=2, dtype=dtypes.float, st=ShapeTracker(views=(View(shape=(1024, 1024, 1024), strides=(0, 1, 1024), offset=0, mask=None, contiguous=False),)))
Segmentation fault (core dumped)
```

**Comment by nimlgen** [comment]
Can you run with gdb and share backtrace (py-bt)?

**Comment by Hprairie** [comment]
Yeah looks like a conda issue. Here is the stack trace.

```bash
```

**Comment by Notnaton** [comment]
I ran into this issue outside conda, just using pip install git+https....
Ran the example code and got a seg fault

**Comment by Notnaton** [comment]
Using version 0.8.0 using pip, works.

**Comment by Hprairie** [comment]
@nimlgen I have been looking through the code base to try to see how it is generating the source of "/usr/local/src/conda/python-3.11.8/Modules/_ctypes/cfield.c", but have been unsuccessful. Any ideas on where to start debugging? I would prefer to use the main branch of tinygrad rather than 0.8.0.

**Comment by nimlgen** [comment]
```
      args_st = self.args_struct_t.from_address(kernargs)
      for i in range(len(args)): args_st.__setattr__(f'f{i}', args[I])
```
is `kernargs` 0 here?

Do you have an integrated gpu? You can manage visible gpus with https://rocm.docs.amd.com/en/latest/conceptual/gpu-isolation.html#rocr-visible-devices if it is the case.

**Comment by Hprairie** [comment]
kernargs isn't zero for me. I have a dedicated GPU, 7900 XTX. 

```bash
(tiny) prairie@TRX40:~/Projects$ DEBUG=3 python3 -c "from tinygrad import Tensor;
N = 1024; a, b = Tensor.rand(N, N), Tensor.rand(N, N);
c = (a.reshape(N, 1, N) * b.T.reshape(1, N, N)).sum(axis=2);
print((c.numpy() - (a.numpy() @ b.numpy())).mean())"
opening device METAL from pid:8864
opening device HSA from pid:8864
opening device NPY from pid:8864
*** CUSTOM     1 custom_random                          arg   1 mem  0.00 GB 
*** CUSTOM     2 custom_random                          arg   1 mem  0.01 GB 
  0 ━┳ STORE MemBuffer(idx=0, dtype=dtypes.float, st=ShapeTracker(views=(View(shape=(1024, 1024, 1), strides=(1024, 1, 0), offset=0, mask=None, contiguous=True),)))
  1  ┗━┳ SUM ((2,), dtypes.float)
  2    ┗━┳ MUL 
  3      ┣━━ LOAD MemBuffer(idx=1, dtype=dtypes.float, st=ShapeTracker(views=(View(shape=(1024, 1024, 1024), strides=(1024, 0, 1), offset=0, mask=None, contiguous=False),)))
  4      ┗━━ LOAD MemBuffer(idx=2, dtype=dtypes.float, st=ShapeTracker(views=(View(shape=(1024, 1024, 1024), strides=(0, 1, 1024), offset=0, mask=None, contiguous=False),)))
> /home/prairie/Projects/tinygrad/tinygrad/runtime/ops_hsa.py(88)__call__()
-> kernargs = self.device.alloc_kernargs(self.kernargs_segment_size)
(Pdb) n
> /home/prairie/Projects/tinygrad/tinygrad/runtime/ops_hsa.py(89)__call__()
-> args_st = self.args_struct_t.from_address(kernargs)
(Pdb) p kernargs
130574266138624
(Pdb) 
```

**Comment by directrix1** [comment]
I also, have this problem with 7900 XT gpu. It does work on 0.8.0 .

**Comment by wozeparrot** [comment]
If you run tinygrad through anything that is not conda does the issue still exist? like in a venv?

**Comment by directrix1** [comment]
In my case, it is installed in a venv. No conda.

**Comment by wozeparrot** [comment]
It's hard to debug this since I'm not able to reproduce it and I've been testing some of the most convoluted python setups. Since the issue seems to be happening inside of ctypes I'm not sure there is much we can do on the tinygrad side.

**Comment by nimlgen** [comment]
I am trying to reproduce that one more time as well. Somebody who can reproduce that, is args passed to `P_set` before segfault (ptr & value) and the value `kernargs ` are the same? With gdb can you write to the `kernargs` address?

**Comment by Hprairie** [comment]
I am a little confused about what you need. I'm a little confused what you mean by the args passed to `P_set`.

**Comment by nimlgen** [comment]
notnaton published a trace where segfault happened at function `P_set`: `P_set (ptr=0x7ffec0a00000, value=, size=) at ./Modules/_ctypes/cfield.c:1462`

**Comment by wozeparrot** [comment]
`HSA` was removed, feel free to reopen if this happens with `AMD`

**Comment by Hprairie** [comment]
Seem's like this might be fixed with the new AMD, however, a different error appears. I have submitted a new issue.
