### ISSUE TITLE
Update Llama examples and benchmarks to Llama 3

### ISSUE THREAD

**Issue by EwoutH** [tinygrad/tinygrad#4267]
Currently the [Llama model](https://github.com/tinygrad/tinygrad/blob/master/extra/models/llama.py) and example and the [Llama example](https://github.com/tinygrad/tinygrad/blob/master/examples/llama.py) in tinygrad are using older Llama versions. It might be nice to update it to the latest Llama 3, so demonstrate tinygrad performance on state-of-the-art LLMs (for their size).

Llama 3 also has double the context size (8192 tokens instead of 4096), which would allow longer and more memory intensive benchmarks, potentially testing cache levels etc.

Probably useful: https://github.com/meta-llama/llama3/blob/main/llama/model.py

**Comment by EwoutH** [comment]
There are a few changes in llama 3, including with computing and applying rotary embeddings (in the `precompute_freqs_cis` and `apply_rotary_emb` functions) and caching and apply masks in the Attention class.

I think the first decision that needs to be made if we want to add compatibility (possible with a new model (class)) and keep exiting Llama 1/2 compatibility, or if we want to update to Llama 3 while dropping older versions.

**Comment by 0i0** [comment]
started implementing https://github.com/0i0/tinygrad/blob/llama3-support/examples/llama3.py
but OOM on my machine, hopfully will be usefull to someone

**Comment by wozeparrot** [comment]
Closed with #4339
