### ISSUE TITLE
Less strict in enforcing a Tensor being used in forward pass?

### ISSUE THREAD

**Issue by ziliangpeng** [tinygrad/tinygrad#4325]
It seems tinygrad is being quite strict in ensuring a Tensor has grad (used in forward). https://github.com/tinygrad/tinygrad/blob/master/tinygrad/tensor.py#L652
```
    for t0 in reversed(self.deepwalk()):
      if t0.grad is None: raise RuntimeError(f"tensor {t0} has no grad")
```

This makes it less easy to play with stuff (running WIP model, having unused Tensor lingering as part of model).

Can we make it less strict about this validation, at least in some sort of debug mode (DEBUG>3)? Can we skip those tensors during backward, instead of `raise`?

**Comment by chenyuxyz** [comment]
can you provide a full example for what you are trying to do?
