### ISSUE TITLE
Examples/conversation.py invalid load key from torch_load() checkpoint dict

### ISSUE THREAD

**Issue by ixns** [tinygrad/tinygrad#4347]
Hi, I am trying to run the conversation.py file, getting this error:

IXNUS :: ~/fun/tinygrad ‹master› % PHONEMIZER_ESPEAK_LIBRARY="/opt/homebrew/Cellar/espeak/1.48.04_1/lib/libespeak.dylib" python3 examples/conversation.py
\/Users/ixns/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
[nltk_data] Downloading package punkt to /Users/ixns/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
ram used:  0.11 GB, decoder.mask                                      : 100%|████████████| 168/168 [00:00<00:00, 2405.91it/s]
loaded weights in  79.98 ms, 0.08 GB loaded at 0.94 GB/s
Traceback (most recent call last):
  File "/Users/ixns/fun/tinygrad/examples/conversation.py", line 261, in <module>
    synth, emotion_embedding, text_mapper, hps, model_has_multiple_speakers = init_vits(args.vits_model_to_use, args.vits_emotion_path, args.vits_speaker_id, args.vits_seed)
  File "/Users/ixns/fun/tinygrad/examples/conversation.py", line 166, in init_vits
    net_g = load_model(text_mapper.symbols, hps, model_config)
  File "/Users/ixns/fun/tinygrad/examples/vits.py", line 535, in load_model
    _ = load_checkpoint(fetch(model[1]), net_g, None)
  File "/Users/ixns/fun/tinygrad/examples/vits.py", line 540, in load_checkpoint
    checkpoint_dict = torch_load(checkpoint_path)
  File "/Users/ixns/fun/tinygrad/tinygrad/nn/state.py", line 145, in torch_load
    _, _, _, rwd, _, ids, base_offset = pkl.load(), pkl.load(), pkl.load(), f.tell(), pkl.load(), pkl.load(), f.tell()
**_pickle.UnpicklingError: invalid load key, '<'.**

**Comment by chenyuxyz** [comment]
duplicate #3118
