### ISSUE TITLE
llama 2 70B not usable on tinybox green

### ISSUE THREAD

**Issue by wozeparrot** [tinygrad/tinygrad#4367]
`CUDA=1 python3 examples/llama.py --gen 2 --size 70B --shard 6 --prompt "Hello." --count 10 --temperature 0 --timing`

Runs out of host memory at loading 90% of the weights.

**Comment by nimlgen** [comment]
Yeah, NV should be a bit better but also OOMs. Wrote a custom allocator to fit it better, but it OOM when creating graphs. Is there any way to remove this reserved memory (like it stops when it has >500ms and requesting ~80mb)?

**Comment by geohot** [comment]
It's not the GPU memory that's the problem AFAIK, it's the host memory not being freed.

**Comment by rheaton64** [comment]
Just got my tinybox green the other day, and running into the same issue. Entire PC freezes at 89% loading and I have to manually restart the machine. Have there been any updates on this?

**Comment by chenyuxyz** [comment]
`NV=1 MAX_CONTEXT=256 python3 examples/llama.py --gen 2 --size 70B --shard 6 --prompt "Hello." --count 10 --temperature 0  --timing` works now and is added to green tinybox CI #5905 .
