### ISSUE TITLE
example/gpt2 benchmark cannot achieve 2ms

### ISSUE THREAD

**Issue by L1aoXingyu** [tinygrad/tinygrad#4386]
I just run gpt benchmark as below on 3090, but I cannot reproduce the 2ms speed in bounties sheet.

```shell
JIT=1 python3 examples/gpt2.py --timing
```

```shell
...
ran model in   5.90 ms

ran model in   5.91 ms

ran model in   5.92 ms

ran model in   5.93 ms

ran model in   5.93 ms
...
```

Is anything wrong for my testing?

**Comment by nimlgen** [comment]
You need to use half + beam. Beam might take some time to optimize. You can use DEBUG=2 to follow the progress of beam, but remove DEBUG=2 to get the full performance on the next run.

`CUDA=1 JIT=1 HALF=1 BEAM=2 CACHELEVEL=0 JIT_BATCH_SIZE=4 python3 examples/gpt2.py --count 10 --temperature 0 --timing`

**Comment by L1aoXingyu** [comment]
oh I see, beam not beam search in LLM but beam in tinygrad

**Comment by L1aoXingyu** [comment]
for achieving 2ms -> 1ms, please shed some light on it, maybe using speculative sampling as kernel and graph are all optimized and some inference mechanism may come to help?
