### ISSUE TITLE
tinyllama training?

### ISSUE THREAD

**Issue by L1aoXingyu** [tinygrad/tinygrad#4433]
is there any code for training tinyllama, I just saw the code for llama inference.

**Comment by geohotstan** [comment]
There's a [500$ bounty](https://docs.google.com/spreadsheets/d/1WKHbT-7KOgjEawq5h5Ic1qUWzpfAzuD_J06N1JwOCGs/edit#gid=0) for "Training TinyLlama with >50% MFU"

**Comment by L1aoXingyu** [comment]
so there is no any basic training code with low MFU to use, right?

**Comment by L1aoXingyu** [comment]
maybe I should add the baseline code for tinyllama training?
