### ISSUE TITLE
how to do anything?

### ISSUE THREAD

**Issue by ziereis** [tinygrad/tinygrad#4434]
how do things like this not work and don't even give any useful error message?

```
t1 = Tensor(np.random.randn(4096, 4096), device="cpu")
t2 = t1.sum()
t2.numpy()
```
gives random import error instead of just printing the available backends 

now i found how to print the devices myself, good.
['PYTHON', 'NV', 'AMD', 'HSA', 'LLVM', 'GPU', 'CLANG', 'CUDA', 'NPY', 'RHIP', 'DISK', 'METAL']
using

what is the numpy backend? idk npy i guess?

another random error:

```
t1 = Tensor(np.random.randn(4096, 4096), device="npy")
t2 = t1.sum()
t2.numpy()
```
AssertionError: compiler is required to build AST

**Comment by geohot** [comment]
cpu isn't a device. Try CLANG or LLVM. For 1.0, we'll rename one of them to CPU.
