### ISSUE TITLE
Too much shared data in ptxas compile

### ISSUE THREAD

**Issue by satin-spirit** [tinygrad/tinygrad#4811]
I am not sure what exactly triggers this, but when using `BEAM=2` I get an error like this after ~15-30 minutes of beam search.
```
tinygrad.device.CompileError: compile failed: ptxas error   : Entry function 'r_64_64_2_4_32_48_4_2_4_2' uses too much shared data (0x10000 bytes, 0xc000 max)
```
I'm not incredibly familiar with the guts of tinygrad. Should this error just be caught and ignored? If so, I can probably make a PR for that.

**Comment by geohot** [comment]
Yea, BEAM should already be ignoring that...not sure why it crashed on this

**Comment by chenyuxyz** [comment]
I made BEAM not ignoring our `CompileError`, as this means tinygrad is generating invalid codes. Ignoring compile error hid some legit bugs before.

**Comment by satin-spirit** [comment]
It does run just fine without BEAM. Though, it's a little concerning to me that tinygrad can output invalid kernels in the first place. For example, what if this error happens when BEAM is disabled, just by chance? Then the user wouldn't have any real way to continue. As far as I can tell, kernels are generated deterministically w/out BEAM. Seems like a bug worth fixing.

**Comment by satin-spirit** [comment]
Closing this as the original issue was fixed and works great now. Thank you!
