### ISSUE TITLE
Error when run llama on A4000

### ISSUE THREAD

**Issue by Bing1002** [tinygrad/tinygrad#4825]
tinygrad.device.CompileError: compile failed: <null>(17): error: more than one user-defined conversion from "nv_bfloat16" to "half" applies:
            function "__half::__half(float)" (declared at line 214 of /usr/local/cuda/include/cuda_fp16.hpp)
            function "__half::__half(short)" (declared at line 227 of /usr/local/cuda/include/cuda_fp16.hpp)
            function "__half::__half(unsigned short)" (declared at line 228 of /usr/local/cuda/include/cuda_fp16.hpp)
            function "__half::__half(int)" (declared at line 229 of /usr/local/cuda/include/cuda_fp16.hpp)
            function "__half::__half(unsigned int)" (declared at line 230 of /usr/local/cuda/include/cuda_fp16.hpp)
            function "__half::__half(long long)" (declared at line 231 of /usr/local/cuda/include/cuda_fp16.hpp)
            function "__half::__half(unsigned long long)" (declared at line 232 of /usr/local/cuda/include/cuda_fp16.hpp)
    *((half4*)(data0+alu0)) = make_half4((half)(val0),(half)(val1),(half)(val2),(half)(val3));

**Comment by nimlgen** [comment]
What's your cuda version?

**Comment by Bing1002** [comment]
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Feb__7_19:32:13_PST_2023
Cuda compilation tools, release 12.1, V12.1.66
Build cuda_12.1.r12.1/compiler.32415258_0

**Comment by Esmail-ibraheem** [comment]
Steps to Fix the Issue:

1. **Understand the Type Conflict**:
   - The error message indicates that the conversion functions from `nv_bfloat16` to `half` are ambiguous.
   - The problematic line seems to be:
     ```cpp
     ((half4)(data0+alu0)) = make_half4((half)(val0),(half)(val1),(half)(val2),(half)(val3));
     ```

2. **Specify Explicit Conversions**:
   - One way to resolve this is to ensure explicit conversions to avoid ambiguity. For example, you might need to cast each value explicitly to a specific type.

3. **Check and Modify Code**:
   - Modify the code to explicitly cast `val0`, `val1`, `val2`, and `val3` to the desired type before passing them to `make_half4`.

Here’s an example of how you might adjust the code to resolve this:

```cuda file 
#include <cuda_fp16.h> // Ensure the header file for half-precision is included

__global__ void exampleKernel(...) {
    // Your code setup here

    // Explicitly cast each value to the required type
    half hval0 = static_cast<half>(val0);
    half hval1 = static_cast<half>(val1);
    half hval2 = static_cast<half>(val2);
    half hval3 = static_cast<half>(val3);

    // Use make_half4 with explicitly casted values
    ((half4)(data0 + alu0)) = make_half4(hval0, hval1, hval2, hval3);
}
```

### Steps to Implement the Fix:

1. **Clone the Repository**:
   ```bash
   git clone https://github.com/tinygrad/tinygrad.git
   cd tinygrad
   ```

2. **Identify the Problematic Code**:
   - Search for the CUDA kernel or function where the error occurs.
   - It is likely in a `.cu` or `.cuh` file where CUDA code is defined.

3. **Modify the Code**:
   - Edit the file to include explicit type casting as shown above.
   - Save the changes.

4. **Compile and Test**:
   - Recompile the code to ensure the changes resolve the issue.
   - Run tests to verify that the modification does not introduce new issues.

5. **Submit a Pull Request**:
   - Once the changes are confirmed, commit your changes:
     ```bash
     git add .
     git commit -m "Fix type conversion ambiguity for half precision"
     ```
   - Push the changes and create a pull request on GitHub.

**Comment by geohot** [comment]
If this is still happening, can you resubmit with a full repro?
