### ISSUE TITLE
Bitcasts missing on CStyle backends

### ISSUE THREAD

**Issue by samayala22** [tinygrad/tinygrad#4832]
**Run on PR branch:** https://github.com/tinygrad/tinygrad/pull/4831

**Repro:**

```Python
from tinygrad import Tensor
from tinygrad.ops import UnaryOps, BinaryOps
from tinygrad.dtype import dtypes
from tinygrad.lazy import LazyBuffer
from tinygrad.tensor import Function
 
def fabsfk(d:LazyBuffer) -> LazyBuffer: # returns float32
  assert d.dtype == dtypes.float32
  dint = d.cast(dtypes.int32, True)
  return dint.e(BinaryOps.AND, dint.const(0x7FFFFFFF)).cast(dtypes.float32, True)

def ilogb2kf(d:LazyBuffer) -> LazyBuffer: # returns int32
  assert d.dtype == dtypes.float32
  dint = d.cast(dtypes.int32, True)
  return dint.e(BinaryOps.SHR, dint.const(23)).e(BinaryOps.AND, dint.const(255)).e(BinaryOps.SUB, dint.const(127))

def pow2if(q:LazyBuffer) -> LazyBuffer: # returns float32
  assert q.dtype == dtypes.int32
  return q.e(BinaryOps.ADD, q.const(127)).e(BinaryOps.SHL, q.const(23)).cast(dtypes.float32, True)

def ldexp2kf(d:LazyBuffer, e:LazyBuffer) -> LazyBuffer: # returns float32
  assert d.dtype == dtypes.float32
  assert e.dtype == dtypes.int32
  return d.e(BinaryOps.MUL, pow2if(e.e(BinaryOps.SHR, e.const(1)))).e(BinaryOps.MUL, pow2if(e.e(BinaryOps.SUB, e.e(BinaryOps.SHR, e.const(1)))))

def logk3f(d:LazyBuffer) -> LazyBuffer:
  assert d.dtype == dtypes.float32
  e = ilogb2kf(d.e(BinaryOps.MUL, d.const(1.0/0.75)))
  return ldexp2kf(d, e.e(UnaryOps.NEG))

class Foo(Function):
    def forward(self, x):
        return logk3f(fabsfk(x))
    
base = Tensor([2.0] * 6)
print(Foo.apply(base).numpy())
```

**Expected results:**
```
PYTHON=1 python ../repro.py
[1. 1. 1. 1. 1. 1.]
```
```
CLANG=1 python ../repro.py
[0.25 0.25 0.25 0.25 0.25 0.25]
```

Python is correct, Clang is wrong

**Graph:**

![image](https://github.com/tinygrad/tinygrad/assets/72941105/3a7ad96a-a7fe-4e65-b544-7b34aada6da9)

It seems that bitcasts before views are not rendered. Partial bit of code rendered below:

```C
void E_(int* restrict data0) {
  float precast0 = 2.0f;
  data0[0] = (*((int*)&precast0)); // INITIAL CAST
}
void E_6(int* restrict data0, const int* restrict data1) {
  int val0 = data1[0];
  for (int ridx0 = 0; ridx0 < 6; ridx0++) {
    data0[ridx0] = (val0&2147483647); // MISSING CAST BACK TO FLOAT
  }
}
```

**Comment by chenyuxyz** [comment]
seems to be a bug for `view_supported_devices`. output is correct if I removed "CLANG" from it

**Comment by samayala22** [comment]
I merged master in my branch and the issue is still there. Removing CLANG from `view_supported_devices` does the trick for the moment.

**Comment by chenyuxyz** [comment]
As discussed on discord, this is an issue from the new ops you introduced in the pr. It's not clear if we want the shifts as ops in ast, and if so, that pr needs to address the issue. Based on the examples you provided, I don't think it's a bug in `view_supported_devices` on master

**Comment by samayala22** [comment]
Correct. Upon some more testing, i found that shifts are not the problem. The issue arises from the introduction of bitwise AND and OR ops. There seems to be an incompatibility between how views handle bitcasts and the presence of these new bitwise ops. Will close this issue as it is not relevant to master (but specific to my PR).
