### ISSUE TITLE
Matching engine is slow ($500 bounty)

### ISSUE THREAD

**Issue by geohot** [tinygrad/tinygrad#4878]
Rewrite the matching engine to get a 2x speedup on my machine (intel core ultra 7 155h) in "model lower"

```
jesse@x1:~/tinygrad$ PROFILE=0 python3 test/external/external_benchmark_schedule.py
***** model forward in  67.59 ms
***** model schedule in  16.62 ms
***** model lower in 1507.84 ms
```

Target is 754 ms. Must pass process replay, and will likely be achieved through a rewrite of the matcher and graph rewrite engine.

**Comment by roelofvandijk** [comment]
https://github.com/tinygrad/tinygrad/pull/4882

**Comment by chenyuxyz** [comment]
the script has a lot more than rewriting, it's slower for me with `UOPS_REWRITE=0 PROFILE=0 python3 test/external/external_benchmark_schedule.py`

**Comment by croumegous** [comment]
another ~10% easy gain: https://github.com/tinygrad/tinygrad/pull/4889

**Comment by GabrielZCode** [comment]
Funny , it's slower for you with UOPS_WRITE=0 , on my machine (i9 1900H) on this command :  PROFILE=0 python3 test/external/external_benchmark_schedule.py  is `
***** model forward in  35.23 ms
***** model schedule in  12.32 ms
***** model lower in 18468.31 ms
`

and with UOPS_REWRITE=0  PROFILE=0 python3 test/external/external_benchmark_schedule.py, it's way faster --> `
***** model forward in  41.56 ms
***** model schedule in  13.65 ms
***** model lower in 1410.08 ms
`

**Comment by abgita** [comment]
Another small gain https://github.com/tinygrad/tinygrad/pull/5047

**Comment by DKormann** [comment]
not sure if this is possible just by rewriting matcher and graph rewrite.
printing the time spend in graph_rewrite i get only 353ms out of 1068ms total for model lower

**Comment by chenyuxyz** [comment]
this was considered done and bounty awarded. there's a new $400 bounty for 2X the speed
