### ISSUE TITLE
Unify lazy.py reduce split with OptOpts.GROUP

### ISSUE THREAD

**Issue by geohot** [tinygrad/tinygrad#4910]
These are the same thing, the only difference is that lazy.py reduce split uses a global buffer instead of a local buffer, and as a consequence outputs two kernels.

The lazy.py reduce split should be moved after the scheduler into `lower_schedule_item`. We have to support that a ScheduleItem may produce 0-n ExecItems. We currently have two fake execitems, `ViewOp` and `EmptyOp`

**Comment by chenyuxyz** [comment]
track in #5542
