### ISSUE TITLE
IDIV may return float. Integer division by zero does not error like PyTorch

### ISSUE THREAD

**Issue by junjunjd** [tinygrad/tinygrad#5005]
#4887 introduces IDIV as `BinaryOps.IDIV: lambda x, y: int(x/y) if y != 0 else x*math.inf`. This may return float as a result to integer division.

PyTorch errors when handling integer division by zero:
```
a, b = torch.tensor([1], dtype=int), torch.tensor([0], dtype=int)
a//b
RuntimeError: ZeroDivisionError
``` 

In tinygrad, Integer division 1//0 yields different results between `int8`/`int32` and `int64`
```
python3 -c "from tinygrad import Tensor, dtypes;a, b = Tensor([1], dtype=dtypes.int8), Tensor([0], dtype=dtypes.int8);c= a.div(b,upcast=False);print(c.numpy())" 
[-1]
```
```
python3 -c "from tinygrad import Tensor, dtypes;a, b = Tensor([1], dtype=dtypes.int32), Tensor([0], dtype=dtypes.int32);c= a.div(b,upcast=False);print(c.numpy())"
[-1]
```
```
python3 -c "from tinygrad import Tensor, dtypes;a, b = Tensor([1], dtype=dtypes.int64), Tensor([0], dtype=dtypes.int64);c= a.div(b,upcast=False);print(c.numpy())"
[0]
```

**Comment by chenyuxyz** [comment]
I think torch errors only if it's on CPU. On MPS it's `tensor([9223372036854775807], device='mps:0')`, on cuda it is `tensor([4294967295], device='cuda:0')`, and on hip it's `tensor([2], device='cuda:0')`. Generally gpu does not throw errors.

**Comment by chenyuxyz** [comment]
You can add `DEBUG=4` to see the kernel code. In this case, it's just `data1[0]/data2[0]` for different int type. And the result is device/target/compiler dependent. I don't think we want to work around that in tinygrad level.

with PYTHON backend (`PYTHON=1`) it throws `TypeError: 'float' object cannot be interpreted as an integer`, which might also be okay
