### ISSUE TITLE
Proof or disproof of the mergeability of two arbitrary ShapeTrackers in Lean (see docs/reshape_without_symbolic.md)

### ISSUE THREAD

**Issue by Humbulani1234** [tinygrad/tinygrad#5054]
I have tried to look for the file `(see docs/reshape_without_symbolic.md)` in the source in relation to this bounty to no success. Is the file located somewhere else than the `docs/` directory?

Actually doesn't this PR #2218 already address this bounty?

**Comment by chenyuxyz** [comment]
I have updated the bounty sheet to point to #2218. It's the same file added to that pr and we later deleted it.

#2218 is a practical attempt to solve a specialized case, and it did improve some cases in shapetracker merging. What we are looking for the bounty is a formal proof to show the complete conditions.
