### ISSUE TITLE
hash and eq for UOp: proposal / clarification request

### ISSUE THREAD

**Issue by DKormann** [tinygrad/tinygrad#5074]
to make _match and rewrite graph simpler would like to make UOp have a hash function based on its components.
probably would need to make it frozen

is this a bad idea? was reading related issues but maybe not enough

**Comment by DKormann** [comment]
if I understand correctly UOp.cmp_tuple is only existing to make > < work deterministically which is needed for deterministic ordering?
could replace that
might save a chunk of lines

**Comment by DKormann** [comment]
could make hash of switched src be the same if op is commutative

**Comment by Qazalin** [comment]
so in general hash is very slow - Have you benchmarked how hash would work?
If you freeze the UOp you should also create a new class from scratch every time, how does that impact rewrite perf?

**Comment by DKormann** [comment]
as long as you cache your hash should be fine?
creating UOp from scratch also in my experience super cheap.

however i am also seeing more clearly the advantages now of tinygrad used uops until now with hash and eq being tied essentially to the object.
