### ISSUE TITLE
t.shard(axis=0) does not free unused parts of buffer in origin device

### ISSUE THREAD

**Issue by chaosagent** [tinygrad/tinygrad#5097]
```
>>> devices = [f"AMD:{i}" for i in range(6)]
>>> t = Tensor.empty(4096, 4096)
>>> t.shard_(devices, axis=0).realize()
>>> print(t.lazydata.lbs[0].buffer.base.size)
16777216
>>> print(t.lazydata.lbs[1].buffer.base.size)
2797568
```

Proposed solution: add a flag `allow_buffer_view=True` to Tensor.contiguous, plumb it through function.py, and make LoadOps.VIEW optional in lazy.py somehow. We want to enable subbuffer creation for ephemeral tensors but not long-living ones or input data; set this flag to False in MultiLazyBuffer.from_sharded.

Alternate solution (hack): In LazyBuffer.copy_to_device, do a copy (somehow) even if src.device = dst.device as long as the src op is LoadOps.VIEW

Other idea: Don't allow user to have Tensors with viewed Buffers at all (ie view the buffers internally for copies and memory scheduling)

Workaround: As the user, don't shard tensor that is already on one of the devices.

Don't know what is good.

**Comment by chenyuxyz** [comment]
fixed by #5122
