### ISSUE TITLE
llama chat mode asserts

### ISSUE THREAD

**Issue by nimlgen** [tinygrad/tinygrad#5200]
`PYTHONPATH=. python3 examples/llama.py --model ../.cache/tinygrad/downloads/llama3-8b-sfr/model.safetensors.index.json --gen 3`

Got this typing:
```
User: ye
Traceback (most recent call last):
  File "/home/nimlgen/tinygrad/examples/llama.py", line 466, in <module>
    assert toks == new_toks[:len(toks)]
AssertionError
```

**Comment by chenyuxyz** [comment]
I think this is due to llama3 changed the tokenizer from sentencepiece to tiktoken. tiktoken uses a different encode merge algorithm and does not have the property that tokenize(old prompt) + tokenize(output) = tokenize(old prompt + output)

**Comment by wozeparrot** [comment]
yea, that assertion doesn't hold true for llama3, can probably just gate the assertion on the llama version being under 3.
