### ISSUE TITLE
Use UOps.VECTORIZE for consts

### ISSUE THREAD

**Issue by Qazalin** [tinygrad/tinygrad#5313]
const renderers have an extra call for rendering a vectorized const. This can simplify to:
```
  # returns a str expression of the const with the given type
  def render_const(self, x:ConstType, dtype:DType) -> str:
    if math.isnan(x): return self.render_cast("NAN", dtype)
    elif math.isinf(x): return self.render_cast(("-" if x < 0 else "") + "INFINITY", dtype)
    elif dtype == dtypes.bool: return "1" if x else "0"
    elif dtype == dtypes.float: return f"{x}f"
    return str(x)
```

Current UOp:
`UOp(UOps.CONST, dtypes.float.vec(4), (), 0.0)`
Desired:
`UOp(UOps.VECTORIZE, dtypes.float.vec(4), (UOp(UOps.CONST, dtypes.float, (), 0.0), ))`

Should also fix DEFINE_ACC's extra type_verify assert.

**Comment by ranjanmangla1** [comment]
new to project, can I take this one?
