### ISSUE TITLE
idx simplification given valid

### ISSUE THREAD

**Issue by chenyuxyz** [tinygrad/tinygrad#5761]
see https://github.com/tinygrad/tinygrad/issues/1801

**Comment by geohot** [comment]
So VALIDHACKS is distinct from normal idx simplification.

Normally, you still need the valid if statement, you just might be able to remove clauses from the idx computation that only are relevant when valid is 0.

In images, any idx that's out of bounds will return invalid. So you don't need valid clauses if you can ensure the idx is out of bounds when it's invalid.

**Comment by chenyuxyz** [comment]
yea for VALIDHACKS the valid clause can be dropped, the idx part should be simplified the same way regardless

**Comment by chenyuxyz** [comment]
done in https://github.com/tinygrad/tinygrad/pull/6740

image and buffer shared the some idx simplification given valid logic, and for image it also checks if we can drop valid
