### ISSUE TITLE
Training with MCTS Optimized Kernels

### ISSUE THREAD

**Issue by nanowell** [tinygrad/tinygrad#5809]
Is there a way to search for optimizations and save them for a training run?

**Comment by nimlgen** [comment]
setting `BEAM` envvar to >=100 will make tinygrad optimizing kernels you run with MCTS. run tinygrad code with `DEBUG=2 BEAM=100` to see how it optimizes kernels. It remembers the search results for each kernel, running next runs with the same `BEAM` value reuses them from cache
