### ISSUE TITLE
PF8 Supporton Nvidia

### ISSUE THREAD

**Issue by SaintMil0** [tinygrad/tinygrad#5929]
FP8_E4M3 is an 8-bit floating-point format with 4 bits for the exponent and 3 bits for the mantissa. It efficiently represents real numbers but with limited precision compared to standard floats. In our code, the FP8_E4M3 class allows conversion between floats and FP8, and performs arithmetic operations. We tested these features to ensure correct handling of addition, multiplication, underflow, and overflow in the FP8 format.

**Comment by nimlgen** [comment]
What's the point of this issue? Put up a good/clean PR when it works in tinygrad and passes all tests.
