### ISSUE TITLE
Release 0.9.2 to Fix the Attribution Error Due to BatchNorm in Beautiful MNIST Example in 0.9.1

### ISSUE THREAD

**Issue by QuentinWach** [tinygrad/tinygrad#5972]
When pip installing the most recent 0.9.1 tinygrad release, examples/beautiful_mnist.py returns an AttributeError: module 'tinygrad.nn' has no attribute 'Batchnorm'. Did you mean: 'BatchNorm2d'? 

This error has been fixed by geohot already but not yet released.

**Comment by wozeparrot** [comment]
we are planning to tag 0.9.2 sometime either this or next week
