### ISSUE TITLE
Out-Of-Memory (OOM) issues when loading large state dictionaries

### ISSUE THREAD

**Issue by artistlu** [tinygrad/tinygrad#5995]
I've encountered an issue with the load_state_dict function when trying to load large state dictionaries for my deep learning models. The function causes OOM errors, which is a significant problem as it prevents me from properly loading pre-trained weights and limits the size of models I can work with.

Problem Description:

The load_state_dict function is responsible for loading the weights from a state dictionary into a PyTorch model. However, when the state dictionary is large, the function can consume a large amount of memory, leading to OOM errors.

This issue is particularly problematic when working with large models or when fine-tuning models with pre-trained weights. The inability to load the state dictionary effectively prevents me from using these models, which significantly limits the scope of my work.

<img width="946" alt="image" src="https://github.com/user-attachments/assets/a131d678-2fb6-40b1-8c59-160f5076d4f6">

**Comment by AlexCheema** [comment]
This issue may belong better in the exo repo: https://github.com/exo-explore/exo

Some questions for you:
- What device are you running on?
- What model are you using?
- What commit hash of exo are you running on?
