### ISSUE TITLE
GRAPH=1 Does Not Work On Windows

### ISSUE THREAD

**Issue by QuentinWach** [tinygrad/tinygrad#6034]
Setting GRAPH=1 to display a model using `engine.graph.py` on Windows doesn't work since **there is no /tmp/ directory on Windows**.
Possibly change this to save the image in the local directory?

**Comment by chenyuxyz** [comment]
you can set GRAPHPATH to change output path https://docs.tinygrad.org/env_vars/
but generally Windows is not a supported system
