### ISSUE TITLE
Add dtypes.void for UOps

### ISSUE THREAD

**Issue by Qazalin** [tinygrad/tinygrad#6045]
You need to update codegen/* and remove the `cast(DType,` stuff in renderer/*.

**Comment by jackhwalters** [comment]
I can take this up

**Comment by jackhwalters** [comment]
Could I have a bit more detail on what needs to be done?

**Comment by Lazarus42** [comment]
Also interested in this. Would be down to pair.

**Comment by mikeest1972** [comment]
I would like to work with @jackhwalters  and @Lazarus42  on this issue. Its my first one also!

**Comment by chenyuxyz** [comment]
#6471
