### ISSUE TITLE
Question on tinygrad flux + MCTS optimization

### ISSUE THREAD

**Issue by anthony0727** [tinygrad/tinygrad#6759]
I tried optimizing flux in tinygrad on H100.
https://github.com/anthony0727/flux-tinygrad-opt

The inference time measure of raw flux seems to be too slow.

Could you give me a hint if I'm missing something?

Optimization Method | Time (ms)
-- | --
RAW | 201654.093
HC | 7989.641
TC | 6317.517
BEAM | 594.451
MCTS | 825.108

**Comment by wozeparrot** [comment]
hcopt is there for a reason, raw time looks correct

**Comment by anthony0727** [comment]
Trying to compare with torch.compile, which gave ~40% speed up compared to original raw flux,
but above observation shows ~300 times speed up with beam search.

I found this quite doubtful, but if I implemented correctly, this is interesting.

**Comment by wozeparrot** [comment]
torch.compile isn't the same thing as our beam search or mcts search. our raw kernels are not the same as torch raw kernels.
