### ISSUE TITLE
SymbolicShapeTracker

### ISSUE THREAD

**Issue by geohot** [tinygrad/tinygrad#681]
Right now, the transformer can't be jitted.

You should be able to pass in a symbolic number and use it in shapes, forcing the codegen to generate kernels that can be parameterized.

**Comment by geohot** [comment]
There's a $1000 bounty for this "SymbolicShapeTracker/RuntimeDimension in JIT, full JIT of LLaMA"

**Comment by Nike682631** [comment]
Can I work on this?

**Comment by geohot** [comment]
You don't need permission

**Comment by AntonioR321** [comment]
I would work on it too))

**Comment by arvganesh** [comment]
Can you elaborate on "using [the symbolic number] in shapes?"

**Comment by python273** [comment]
try to run llama with debug. It recompiles kernels, since the shapes are changing with each added token
```
# purple is jitted
PYTHONPATH=. DEBUG=2 JIT=1 CLANG=1 python3 examples/llama.py --prompt "I like"
```

**Comment by chenyuxyz** [comment]
@wozeparrot this is done
