### ISSUE TITLE
nn.conv should support padding='same'

### ISSUE THREAD

**Issue by geohot** [tinygrad/tinygrad#6901]
Needs extensive tests to confirm behavior matches torch

**Comment by KunalKumar-1** [comment]
hey @geohot  What types of extensive tests would you recommend running to validate that the new padding='same' functionality behaves identically to existing PyTorch convolution layers? Should we test different kernel sizes, stride values, input sizes, and padding modes?

**Comment by wilhelmagren** [comment]
Hi, I've been working on this but don't have too much time rn to complete it. If someone else is close to done, could you @ me in this thread to let me know its already been resolved? 

Thanks,
