### ISSUE TITLE
Add support for logcumsumexp

### ISSUE THREAD

**Issue by geohot** [tinygrad/tinygrad#6911]
Matching https://pytorch.org/docs/stable/generated/torch.logcumsumexp.html

**Comment by KunalSin9h** [comment]
working on it @geohot

**Comment by chenyuxyz** [comment]
also needs `cummax` for stability

**Comment by KunalSin9h** [comment]
ok @chenyuxyz

**Comment by the-praxs** [comment]
Working on it in #6915

**Comment by jeffzh4ng** [comment]
@geohot @chenyuxyz can you take a look at https://github.com/tinygrad/tinygrad/pull/6921?

**Comment by chenyuxyz** [comment]
merged. might no be the most stable way to write it but we can revisit it later, it's on par with other numerically questionable methods
