### ISSUE TITLE
fold_unrolled_divs doesn't work on small expressions

### ISSUE THREAD

**Issue by S-Lykles** [tinygrad/tinygrad#6935]
`fold_unrolled_divs`  in `ops.py` is meant to rewrite expression like:
x//4+(x+1)//4+(x+2)//4+(x+3)//4 -> x

When the max of x is smaller than one of the denominators, some of the individual terms are already folded. 
For example `x[0-3]//4` becomes `x` and then this pattern is not detected anymore.

I wrote a quick test, currently it will fail. 
```python
  def test_arange_unrolled4_small(self):
    gidx = Variable("gidx", 0, 3)
    unrolled_div = (gidx)//4+(gidx+2)//4+(gidx+3)//4+(gidx+1)//4
    self.helper_test_variable(unrolled_div, 0, 3, "gidx")
```

**Comment by chenyuxyz** [comment]
addressed in https://github.com/tinygrad/tinygrad/pull/6977
did not change if there's only term left (e.g., only `(x+3)//4`), as i think it might belong to `div_folding` instead of `fold_unrolled_divs`

**Comment by S-Lykles** [comment]
(x[0-1]+3)//4 fails for the same reason as (3*x[0-3]+3)//4
I found this issue because I was working on an algorithm that would fold things like 
(3*x[0-1]+3) // 4 and (3*x[0-3]+3) % 4
They are foldable because
(3*x[0-3]+3) % 4 = ((3-4)*x[0-3]+3) % 4
and we already know that:
(-x[0-3] + 3) % 4 = (-x[0-3] + 3)
because the min and the max are between 0 and 4

Basically if some mod expression is congruent to an expression who's min and max are between 0 and the mod then it can be folded.
