### ISSUE TITLE
EfficientNet Example from the Documentation Doesn't Work

### ISSUE THREAD

**Issue by AdrianoWeid** [tinygrad/tinygrad#7113]
I recently came across tinygrad and went through the documentation. When I tried to run the EfficientNet example provided, it unfortunately doesn't work as expected.

I followed the steps from the guide:

```bash 
git clone https://github.com/tinygrad/tinygrad.git
cd tinygrad
python3 -m pip install -e .
python3 examples/efficientnet.py webcam
```
However, I receive the following error message:

```bash 
ModuleNotFoundError: No module named 'extra'
```
Is there a known fix for this problem, or does the documentation need to be updated to include additional steps?

**Comment by wozeparrot** [comment]
does it work with `PYTHONPATH=. python3 examples/efficientnet.py webcam`?

**Comment by AdrianoWeid** [comment]
> does it work with `PYTHONPATH=. python3 examples/efficientnet.py webcam`?

Thanks, that worked! Is there a reason why this isn't included in the documentation or is this a special occurrence?
