### ISSUE TITLE
Creating tensors from blob with QCOM=1 fails

### ISSUE THREAD

**Issue by haraschax** [tinygrad/tinygrad#7151]
I would expect these asserts to pass. The last assert fails with QCOM=1. They pass with CLANG=1 on PC. It's important to be able to create Tensors backed by numpy array so we can run a model quickly with a jit without needing to create tensors on every iteration.

```
import numpy as np
from tinygrad.tensor import Tensor
from tinygrad.dtype import dtypes
from tinygrad.helpers import getenv, to_mv, mv_address


a_np = np.ones((1,1), dtype=np.float32)
a_t = Tensor.from_blob(mv_address(a_np), (1,1), dtype=dtypes.float, device='QCOM')
assert a_t.numpy() == a_np
a_np[0,0] = 2
assert a_t.numpy() == a_np
assert a_t.add(1).add(-1).numpy() == a_np
```

**Comment by nimlgen** [comment]
The `from_blob` api wasn't originally designed for that, so this example currently produces a page fault because the passed CPU pointer (`mv_address(a_np)`) is not mapped to the GPU.

We need to consider what api we want here and if we can map the address to the gpu without additional copies.

**Comment by haraschax** [comment]
Do you want to support this? I assume making tensors every iteration will always be slow, so the only other solution I see is to pass CLANG tensors into the jit and have the moved to the GPU inside the jit?

**Comment by geohot** [comment]
Fixed with "NPY" device Tensor
