### ISSUE TITLE
delete LazyBuffer, everything is UOp

### ISSUE THREAD

**Issue by Qazalin** [tinygrad/tinygrad#7697]
1. Smaller big graph - VIEW of BUFFER rewriting to LOAD/PRELOAD
    - #7731
    - #7732
    - #7695
 
2. Track UOp Buffers with WeakKeyDictionary
    - #7742
    - #7745
    - #7746
    - #7743
    - #7766
    - #7946
    - #7912

3. Perfectly match big graph output with `LazyBuffer = UOp`
   - #7818
   - #7819
   - #7820
   - #7849
   - #7867
   - #7907
   - #7905
   - #7940
   - #7941
   - #7944
   - #7956
   - #7968
   - #7976
   - #7989
   - #7992
   - #8004
   - #8005
   - #7801

**Comment by geohot** [comment]
I have a lot of this done in https://github.com/tinygrad/tinygrad/pull/7065, at least re: the methods.

LAZYCACHE should be the normal graph_rewrite dedup, right?

**Comment by Qazalin** [comment]
LAZYCACHE is global, dedup is for a single `.schedule()`.
stunning_mnist style doesn't need more work, but in most benchmarks we `schedule_step`.
