### ISSUE TITLE
AMD unsupported Arch: gfx096

### ISSUE THREAD

**Issue by FlorianHeigl** [tinygrad/tinygrad#7704]
Hi,

I've been upsetting tinygrad a bit.

I started it with (as far as I recall)

```
AMD=1 ROCM=1 exo --inference-engine=tinygrad
```
I tried to find a workaround using ZLUDA (using LD_LIBRARY_PATH)
```
AMD=1 CUDA=1 exo --inference-engine=tinygrad
```
and of course I tried AMD=1 and also GPU=1.
and in most cases I get back the same answer, telling me I've upset tinygrad:
```
Error: Failed to fetch completions: Error processing prompt (see logs with DEBUG>=2): Unsupported arch: gfx906
```
I tried using 
```HSA_OVERRIDE_GFX_VERSION=9.0.6 HIP=1  GPU=1 exo --inference-engine=tinygrad```
but also no luck.

I _think_ it's because you access `/dev/kfd...` anyway, right?

It seems that 
```HSA_OVERRIDE_GFX_VERSION=9.0.6  HIP=1 exo --inference-engine=tinygrad``` does in fact work, there was some GPU activity. though you notice slowness / partial offload. 
As started in #5977 it is just for debugging, so that would make sense.

I've been looking at this for a few days now.
The PR [amd cwsr #6950](https://github.com/tinygrad/tinygrad/pull/6950) seems to be adding such support. I've also found the LLVM reference at https://llvm.org/docs/AMDGPU/AMDGPUAsmGFX906.html - I'm not understanding why with that support generally existing I can't make things work using `CLANG=1`. 
[issue #5977](https://github.com/tinygrad/tinygrad/issues/5977) gave me the idea for trying HIP=1 (no worky)

I understand as much as all AMD=1 incantations were wrong since it is not a RDNA/CDNA card.

So, my question would be - __what combination could be expected to work?__.

The arch `gfx906` refers to radeon pro vii (vega20), it's pretty much the Instinct MI60 with added display outputs. I suppose I can spend a few weeks creating a facsimile of #6950 but I'm not sure if that is needed _at all_. In theory, GPU=1 should work, HIP=1 does kinda work, CLANG=1 should work as there is LLVM support.
(maybe even CUDA=1 via ZLUDA should work - I don't know, it failed in a prerequiste)

Could someone recommend which path is the best to keep trying out?
Sure, there's the path that says "buy Nvidia" but I don't wanna let AMD off the virtual hook in my wallet.

**Comment by nimlgen** [comment]
https://docs.tinygrad.org/runtime/

AMD=1 supports gfx10 and gfx11. Use GPU=1 or HIP=1 (this is mostly for debug, but still supported for now)
