### ISSUE TITLE
suttle bug with duplicate indices in setitem

### ISSUE THREAD

**Issue by ttomsa** [tinygrad/tinygrad#7739]
a = Tensor([1,2,3,4]).reshape(2,2)
a[[0,0], [0,0]] = Tensor([2,0])

a is:
[[2 2] [3 4]] instead of [[0 2] [3 4]]

essentially it doesn't override if it's a 0.
I will look to fix it in a couple of days.

**Comment by geohot** [comment]
I don't understand that example, I don't think that's supposed to work. If you want, add a failing test in a PR you think should pass

**Comment by chenyuxyz** [comment]
isn't that just setitem? it works in numpy and torch and i think we should fix it

**Comment by geohot** [comment]
Oh...I see, sorry. It's using the RHS Tensor as like a queue to pop off of

**Comment by ttomsa** [comment]
I think it's why #7737 is failing

**Comment by geohotstan** [comment]
#7737 is another problem (cuda only weirdness).

One hack for this is to turn the mask into a `nan` mask and do 
`for dim in axis: vb = functools.reduce(lambda x,y: y.isnan().where(x, y), vb.split(1, dim))` 
but this just shifts the "unable to override 0" problem to "unable to override nan"
e.g.
```
a = Tensor([1,2,3,4]).reshape(2,2).float()
a[[0,0], [0,0]] = Tensor([2,float("nan")])
```
would be wrong.

is nan better than 0? haha
(maybe we could now do a Ops.View with arg=Tensors and pattern match that to fancy indexing? :^) )

**Comment by ttomsa** [comment]
Oh yeah my bad, I was looking at the ptx errors and saw when an index was wrong a 0 was involved and realized overriding with 0 doesn't work but I mixed up the actual tensor and desired tensor in my head.
