### ISSUE TITLE
Div mod recombine pattern not always matching

### ISSUE THREAD

**Issue by S-Lykles** [tinygrad/tinygrad#7958]
Some div mod recombine patterns are not always being folded properly at the moment. See #7957 for examples. 
For some reason `div_folding` and `mod_folding` are changing the `x` in the following pattern before this pattern can match.
```python
  (UPat.var("x")%UPat.cvar("c")+(UPat.var("x")//UPat.cvar("c"))*UPat.cvar("c"), lambda x,c: x), # (x%c)+(x//c)*c = x
```

I don't quite understand why because this pattern is higher in the list and I thought the matching was happening from the root.

**Comment by chenyuxyz** [comment]
there's COMMUTATIVE flipping that reorders the add to `((a+((((a*31)+1)//30)*30))+1)` thus no match

**Comment by S-Lykles** [comment]
My point was that `(31 * a + 1) % 30 + ((31 * a + 1) // 30) * 30` should be matched by the `(x%c)+(x//c)*c` pattern first (where `x` is (31*a+1)) before the mod or div expressions are simplified.
What is happening now is that `mod_folding` and `div_folding`  are rewriting the `x%c` part and `x//c` so they don't look like the pattern anymore. What I'm confused by is that the `(x%c)+(x//c)*c` pattern is much higher in the `PatternMatcher` list than the generic `(x%c)` and `(x//c)` patterns so I thought that that implied that `(x%c)+(x//c)*c` would always be matched first.

**Comment by chenyuxyz** [comment]
oh got it. the src gets rewrite first when looking at a node `https://github.com/tinygrad/tinygrad/blob/c068e8c242c1f9f8c78da926a6b8ff4bf7e4eaa1/tinygrad/ops.py#L775`

it's usually what we want, but it's counter productive here
