### ISSUE TITLE
Running inference for big models like stable_diffusion/LLaMa in float16/int8/int4

### ISSUE THREAD

**Issue by kunwar31** [tinygrad/tinygrad#829]
So, float16 may be possible already, but there are problems.
We could cast all the weights to float16, after we have loaded them. But the problem with casting after loading all weights in float32 is that the peak memory usage is 1.5x (first all the weights are loaded in fp32, then casted to fp16) 

Another problem is, setting the default_type for a Tensor does not set the dtype when calling methods like arange, rand, randn

Changes needed:
1. Allow casting weights to a specific dtype in fake_torch_load_zipped
2. Setting default_type for a Tensor should also set dtype in arange, rand and randn.

After trying out hacky ways to implement 1,2 for running stable diffusion, I was able to get the peak memory down, but I started getting domain errors in a couple of math.sqrt used in get_x_prev_and_pred_x0. Tried clipping the inputs to positive values but got a completely black image as the output. I'm looking further into this,  anyone willing to work with me on this is welcome.

For int8/int4 inference, there is another issue already https://github.com/geohot/tinygrad/issues/739, but I think float16 inference is a prerequisite for that

**Comment by kunwar31** [comment]
Update: I figured out the issue, it was with the way I was casting the tensors.  I've got FP16 inference with stablediffusion working. Here's an output for prompt - "a cat in a hat" with 20 steps 
![rendered](https://github.com/geohot/tinygrad/assets/24824080/e702b635-d237-40c8-9ada-00c4ebc3fc06)

**Comment by geohot** [comment]
Sweet! Yea it should work if you cast them as they are being loaded.

**Comment by kunwar31** [comment]
> NOTE: all the math and intermediates for stable diffusion are still float32, changing that will require more work. But float16 weights (save memory / memory bandwidth) work.

@geohot Agreed, BTW for the above run I just ended up changing default_type on Tensor to float16 and changing rand dtype to Tensor.default_type.np. For randn, this becomes an issue `TypeError: Unsupported dtype dtype('float16') for standard_normal`. Looking into it

**Comment by kunwar31** [comment]
@geohot What do you think about having an env var to control the default tensor type?

**Comment by chenyuxyz** [comment]
closing this as complete, it was before all dtype stuff. we support float16, int8, nf4 for llama now (no int8 tc though). and it's straightforward to add more
