### ISSUE TITLE
Use Tensor as Index (e.g. `gather`)

### ISSUE THREAD

**Issue by vwxyzjn** [tinygrad/tinygrad#858]
Hello, this is such a cool project. I was playing with using tinygrad to create some reinforcement learnings scripts, but I ran into a minor issue with using Tensor as Index.

A common thing to do in Deep Q Learning is to use a tensor filled with actions to fetch its corresponding Q values. For example, in the snippet below, there are two batches of q values and actions, and we want to fetch the q values `0` and `6`. We can achieve this feature in torch either using `gather` or just array indexing.

```python
import torch
from tinygrad.tensor import Tensor

q_values = torch.tensor([[1, 2, 3], [4, 5, 6]])
actions = torch.tensor([[0], [2]]) 
print(f"we have q_values: \n{q_values}\nand actions: \n{actions}")
print("q_values.shape", q_values.shape)
print("actions.shape", actions.shape)
print("q_values corresponding to actions", q_values.gather(1, actions).flatten())

actions = torch.tensor([0, 2]) 
print("q_values.shape", q_values.shape)
print("actions.shape", actions.shape)
print("q_values corresponding to actions", q_values[torch.arange(2), actions])
```
```
we have q_values: 
tensor([[1, 2, 3],
        [4, 5, 6]])
and actions: 
tensor([[0],
        [2]])
q_values.shape torch.Size([2, 3])
actions.shape torch.Size([2, 1])
q_values corresponding to actions tensor([1, 6])
q_values.shape torch.Size([2, 3])
actions.shape torch.Size([2])
q_values corresponding to actions tensor([1, 6])
```

After some digging, however, I realized tinygrad does not seem to have similar feature such as `gather`. Tinygrad also does not support Tensor to index arrays, as shown below. As a result, I wasn't sure how to proceed and was wondering if you have any suggestions. Thanks!

```python
from tinygrad.tensor import Tensor
Tensor([[1, 2, 3], [4, 5, 6]])[Tensor([0])]
```
```
Traceback (most recent call last):
  File "/home/costa/Documents/go/src/github.com/vwxyzjn/tinygrad/q_values.py", line 18, in <module>
    Tensor([[1, 2, 3], [4, 5, 6]])[Tensor([0])]
  File "/home/costa/Documents/go/src/github.com/vwxyzjn/tinygrad/tinygrad/tensor.py", line 252, in __getitem__
    new_slice.append((s%sz, s%sz+1) if isinstance(s, int) else (slcfix(s.start, sz, 0), slcfix(s.stop, sz, sz)))
AttributeError: 'Tensor' object has no attribute 'start
```

Btw love your approach to reducing the lines of code. I maintain an RL library called [CleanRL](https://github.com/vwxyzjn/cleanrl), and we employ a similar approach and create highly succinct RL implementations (each is about ~400 LOC). Looking forward to building a variant with `tinygrad`.

**Comment by geohot** [comment]
Oh scatter and gather. So for now, these break the tinygrad model.

But you can emulate this with arange, a compare, and a multiply. See how nn.Embedding does it.

**Comment by geohot** [comment]
Oh I know CleanRL! Would be great to have a tinygrad variant.

I posted in #mlperf-bounties about this on Discord. We should have a gather method incoming very soon. It'll be a little slow because it's using only ADD/MUL and not changing the memory accesses, but for that Q learning case it won't matter in the slightest if your action space is <100.

Will function like torch `input.gather(dim, index)`

**Comment by vwxyzjn** [comment]
Nice thanks! Also, thanks for the reference on `nn.Embedding`. I was able to hack it through for the moment. 

```python
from tinygrad.tensor import Tensor
q_values = Tensor([[1, 2, 3], [4, 5, 6]])
actions = Tensor([0, 2])

manual_gather = Tensor.where(
    actions.unsqueeze(2).expand(*actions.shape, 3) == Tensor.arange(3).reshape(1, 3).expand(*actions.shape, 3),
    Tensor([[1, 2, 3], [4, 5, 6]]),
    0,
).sum(1)
print(manual_gather.numpy())
```
```
[1. 6.]
```
