### ISSUE TITLE
Limit the number of ops which can be evaluated lazily

### ISSUE THREAD

**Issue by kunwar31** [tinygrad/tinygrad#953]
currently, there is no limit to how large the ops backlog can grow, this can cause tinygrad to create kernels which have too many args, leading to compilation warnings and even failures (on OPENCL, CUDA)

```
UserWarning: Kernel 'E_56_4' has 433 arguments with a total size of 3464 bytes, which approaches the limit of 4352 bytes on <pyopencl.Device 'NVIDIA GeForce RTX 3060 Laptop GPU' on 'NVIDIA CUDA' at 0x7ee4820>. This might lead to compilation errors, especially on GPU devices.
```
and when args exceed the limit, 
```
pyopencl._cl.RuntimeError: clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE
```

what about a change like this in LazyBuffer
```
    if isinstance(src, LazyOp):
      self.op: LazyOp = src
      counter = 0
      for x in get_buffers(self.op): 
        x.children.add(self)
        counter += 1
      if counter > 100:
        print('early realize')
        self.realize()
```
Using this I was able to run code which would otherwise create kernel compilation errors 

instead of setting a hardcoded value like 100, there must be a smart way to decide when to realize, so that kernel compilation doesnt fail

**Comment by kunwar31** [comment]
`433 arguments with a total size of 3464 bytes`  means each arg is 8 bytes, and I found the no. of args to be `counter + 1` in my case, so we could calculate max args based on CL_DEVICE_MAX_PARAMETER_SIZE

**Comment by geohot** [comment]
So that counter isn't the right fix. There's two issues here:

1) Limiting the number of buffers passed into a kernel. This should be done in lazy.py and not do the fusion if the parent count is too high.

2) Early realizing. If a buffer is two reduce ops back, realize should probably be kicked off. But that won't generically fix the issue you are describing.

**Comment by kunwar31** [comment]
1. yes, limiting number of buffers passed directly would solve the compilation issue
2. Some form of early realizing would still be needed, as this simple code takes indefinately long time to run because of lazy ops getting accumulated exponentially. 
```
from tinygrad.tensor import Tensor
x = Tensor([1,2,3,4,5])
for _ in range(20):
    x = x+x  #Each addition doubles the ops 
x.realize() 
```

didn't understand the `If a buffer is two reduce ops back, realize should probably be kicked off` part

**Comment by geohot** [comment]
There's a distinction between limiting the ops at fusion and limiting the total ops. If you run that with OPT=0 (but still LAZY), it should be fine I think.

**Comment by chenyuxyz** [comment]
closing as stale. The lazy has changed a lot. Limiting buffer per kernel is tracked in #1461 

notably this piece of code has no problem running now
```
from tinygrad.tensor import Tensor
x = Tensor([1,2,3,4,5])
for _ in range(20):
    x = x+x  #Each addition doubles the ops 
x.realize() 
```
